### ISSUE TITLE
Is it safe to assume `$TMPDIR` will always be set on OSX?

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf-ruby#10]
I noticed this plugin, as well as two of my own, use this to get a temporary directory:

``` bash
  if [ "$TMPDIR" = "" ]; then
    local tmp_download_dir=$(mktemp -d)
  else
    local tmp_download_dir=$TMPDIR
  fi
```

`$TMPDIR` seems to always be set on OSX, but I'm curious if it's ever possible for it not to be. If it's not, this script will fail. `$(mktemp -d)` will always fail on OSX because it expects a directory name template. Is it safe to assume `$TMPDIR` is always set on OSX?

**Comment by HashNuke** [comment]
@Stratus3D as far as I've seen, `$TMPDIR` seems to be set. But I've only checked for OSX `10.11.4` and a version before.

Which version of OSX are you using? Following is my output for `10.11.4`.

```
$ mktemp -d
/var/folders/96/1sp35x9j2n116stp3gtk3m5w0000gn/T/tmp.LopmtidE
```

**Comment by Stratus3D** [comment]
I'm on OSX 10.10.5. This is what I get:

    bash-3.2$ mktemp -d
    usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
           mktemp [-d] [-q] [-u] -t prefix

It's probably safe to assume `$TMPDIR` is always set. I've been searching and haven't found anything that says it might not be. It is however possible to manually unset it (`unset TMPDIR`), so it is possible the script would be run without `$TMPDIR` set.

**Comment by tuvistavie** [comment]
I do not have any computer running OSX to check, but I think we should pass
a template to `mktemp` just in case, as it does not have any drawback.

**Comment by Stratus3D** [comment]
Good idea. I've updated the Lua plugin. I'll put out PRs for the other plugins when I get a chance.

**Comment by Stratus3D** [comment]
I think I've addressed this issue in all the asdf-vm plugins. Closing this issue.
