### ISSUE TITLE
Ruby version not coming from ASDF

### ISSUE THREAD

**Issue by undeniablyrob** [asdf-vm/asdf-ruby#103]
I'm unable to get back to using ASDF after installing rbenv. 

### Steps to Reproduce
1. New laptop with OSX. Follow [instructions to install asdf](https://github.com/asdf-vm/asdf).
1. Get frustrated with something unrelated and install rbenv.
1. [Remove rbenv](https://stackoverflow.com/questions/31173968/how-do-you-uninstall-rbenv-on-osx).

### Expected Behavior
`ruby -v` refers to the local or global ruby version specified in `.tools-version`.

### Actual Behavior
`ruby -v` refers to system ruby (2.3.7, I'm guessing from /usr/local/bin?)

### Environment
OSX Mojava. New laptop with only Homebrew, asdf,and (at one point) rbenv installed.

### Other Notes
Reshimming didn't seem to do anything either. 
``` 
~/src/foo $ asdf install
ruby 2.5.1 is already installed
postgres 10.0 is already installed
nodejs 8.9.4 is already installed

~/src/foo  $ ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
~/src/foo  $ cat .tool-versions
ruby 2.5.1
postgres 10.0
nodejs 8.9.4

~/src/foo $ ruby -v && which ruby
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
/Users/robwilson/.asdf/shims/ruby

~/src/foo $ cat /Users/robwilson/.asdf/shims/ruby
#!/usr/bin/env bash
# asdf-plugin: ruby
# asdf-plugin-version: 2.5.1
exec /Users/robwilson/.asdf/bin/private/asdf-exec ruby bin/ruby "$@"
```

What's the best way to "reset" ASDF?

**Comment by Stratus3D** [comment]
I'm going to guess something in your `PATH` is wrong. Try running `type -a ruby`. It should show you all the different `ruby` executable on your path. The asdf shim should be the first `ruby` that command prints. Based on what you've shared it's definitely not the first `ruby`. My guess rbenv comes before asdf in your `PATH` and so your shell is finding the rbenv-installed `ruby` first.

**Comment by undeniablyrob** [comment]
Ah, yep. That was the issue. Thanks!

**Comment by spencerdcarlson** [comment]
If anyone else came across this issue here is the correct output of `type -a ruby`

**Comment by lucastamoios** [comment]
I was getting the same as @spencerdcarlson while using iTerm with Oh-My-Zsh (bash was giving me the right answer):
```
$ type -a ruby
ruby is /Users/host/.asdf/shims/ruby
ruby is /usr/bin/ruby
```
I solved it by restarting the terminal.

**Comment by nshoes** [comment]
D'oh! Thanks @lucastamoios :)

**Comment by stomachfat** [comment]
All of the above didn't quite work for me - 

I had to prepend `bin/` for command to pick up `asdf`'s ruby version 

e.g. `bin/rails s`

**Comment by jacober9** [comment]
Installed asdf via brew and then installed ruby, but after setting global ruby version via asdf it continued to point to the system ruby version even after terminal refresh.
Turned out the path wasn't added to my .zshrc
I used `echo -e "\n. $(brew --prefix asdf)/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc `
which added `/usr/local/opt/asdf/asdf.sh` to my path and this fixed my problem.

**Comment by KateRezentes** [comment]
pickup-sports % ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
pickup-sports % rails s 
Your Ruby version is 2.6.3, but your Gemfile specified 2.6.5
pickup-sports % ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
pickup-sports % asdf install ruby 2.6.5
ruby 2.6.5 is already installed
pickup-sports % type -a ruby
ruby is /usr/bin/ruby
pickup-sports % 

I cannot figure out what to do here. I even reset my env variables. I need to run ruby 2.6.5, but it keeps running the system version ruby 2.6.3.

**Comment by Stratus3D** [comment]
@KateRezentes , try re-installing ruby 2.6.5:

```
asdf uninstall ruby 2.6.5
asdf install ruby 2.6.5
```

Watch the output from the `install` command. Ruby may fail to install but asdf might get confused and think it was installed successfully.

**Comment by cheesepaulo** [comment]
Guys, just use the doc instructions.

https://asdf-vm.com/guide/getting-started.html#_3-install-asdf

For me was **ZSH & Homebrew**
echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc

It just works.

**Comment by devclaire92** [comment]
> I was getting the same as @spencerdcarlson while using iTerm with Oh-My-Zsh (bash was giving me the right answer):
> 
> ```
> $ type -a ruby
> ruby is /Users/host/.asdf/shims/ruby
> ruby is /usr/bin/ruby
> ```
> 
> I solved it by restarting the terminal.

This works for me! Thank you!

**Comment by EdwinRozario** [comment]
I had **rbenv** installed before. I have uninstalled **rbenv** and deleted all of its references from **.zshrc**. I have **asdf** installed according to the docs. Installed ruby 3.3.5 with asdf. When i run `gem install <any gem>` i am getting the following error.

```
<internal:/Users/username/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in
`require': dlopen(/Users/username/.gem/gems/stringio-3.1.1/lib/stringio.bundle, 0x0009):
Library not loaded: /Users/username/.rbenv/versions/3.3.4/lib/libruby.3.3.dylib (LoadError)
  Referenced from: <AAEC65F9-EA94-3CDA-9A96-407087545A35> /Users/username/.gem/gems/stringio-3.1.1/lib/stringio.bundle
  Reason: tried:
'/Users/username/.rbenv/versions/3.3.4/lib/libruby.3.3.dylib' (no such file),
'/System/Volumes/Preboot/Cryptexes/OS/Users/username/.rbenv/versions/3.3.4/lib/libruby.3.3.dylib' (no such file),
'/Users/username/.rbenv/versions/3.3.4/lib/libruby.3.3.dylib' (no such file) - /Users/username/.gem/gems/stringio-3.1.1/lib/stringio.bundle
```

```
asdf list ruby
*3.3.5
```

```
type -a ruby
ruby is /Users/edwinrozario/.asdf/shims/ruby
ruby is /usr/bin/ruby
```

Dont understand why its still trying to load files from `/.rbenv/` and i am not sure how to fix this. The same is happening system ruby `(2.6.10)` as well. Anyone had the same issue?

**Comment by Stratus3D** [comment]
@EdwinRozario what does `type -a gem` give you? Have you tried running `asdf reshim`?

**Comment by EdwinRozario** [comment]
@Stratus3D `asdf reshim` did not work.

```
type -a gem
gem is /Users/username/.asdf/shims/gem
gem is /usr/bin/gem
```

**Comment by EdwinRozario** [comment]
I had to do `rm -rf ~/.gem` to fix the issue.

**Comment by elvisserrao** [comment]
> Guys, just use the doc instructions.
> 
> https://asdf-vm.com/guide/getting-started.html#_3-install-asdf
> 
> For me was **ZSH & Homebrew** `echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc`
> 
> It just works.

For me, was ```export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"``` that solved the problem. 

It is described on the ZSH instructions. :-)

**Comment by imCorfitz** [comment]
I spent some time troubleshooting this after running a brew upgrade, which also updated my asdf installation. I had removed the asdf-specific PATH entry from my .zshrc (as recommended) but overlooked adding asdf to the list of plugins in my oh-my-zsh configuration. Once I included asdf as a plugin, everything worked as expected.
