### ISSUE TITLE
current ruby and which ruby do not match

### ISSUE THREAD

**Issue by mcountis** [asdf-vm/asdf-ruby#104]
I just uninstalled nvm and rbenv and moved to asdf. I got node working just fine, now asdf is giving me headaches with ruby.

```sh
$ cat .ruby-version 
2.2.2
$ asdf current
nodejs         10.15.1  (set by /Users/mcountis/.tool-versions)
ruby           2.2.2    (set by /Users/mcountis/project/.ruby-version)
$ which ruby
/Users/mcountis/.asdf/shims/ruby
$ asdf which ruby
/Users/mcountis/.asdf/installs/ruby/2.5.3/bin/ruby
$ ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin16]
$ asdf reshim
$ asdf current
nodejs         10.15.1  (set by /Users/mcountis/.tool-versions)
ruby           2.2.2    (set by /Users/mcountis/project/.ruby-version)
$ asdf which ruby
/Users/mcountis/.asdf/installs/ruby/2.5.3/bin/ruby
$ ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin16]
```

The versions of ruby referenced by `asdf current` and `asdf which ruby` do not match. Help please?

**Comment by mcountis** [comment]
Digging deeper into asdf's codebase, it's on their end. Looks like the exec and env commands rank version files differently from current and which.

**Comment by Stratus3D** [comment]
@mcountis is there an asdf issue for this?

**Comment by idabmat** [comment]
@Stratus3D I believe it is this one https://github.com/asdf-vm/asdf/issues/470
I am encountering the same behaviour after upgrading to asdf 0.7
