### ISSUE TITLE
Waste of time when installing ruby version

### ISSUE THREAD

**Issue by faraazahmad** [asdf-vm/asdf-ruby#105]
I recently installed ruby 2.6.1 and didn't already have `libssl-dev libreadline-dev zlib1g-dev` installed on my machine. However, I got to know that these packages were missing on my machine only after the source was downloaded and the installation began (which took a while). 

Is it possible to check for these packages and throw the missing packages error before the source is downloaded and installed? That would save everyone some time

**Comment by SeanSith** [comment]
asdf-ruby uses https://github.com/rbenv/ruby_build to install Rubies. I'd imagine your feedback over there.

I'd reference https://github.com/rbenv/ruby-build/blob/2ecfe4d42a032a73ee4a8ba6b4a43de4512ffbe4/bin/ruby-build#L1069 as a place to improve.

**Comment by Stratus3D** [comment]
@faraazahmad yes please open an issue on https://github.com/rbenv/ruby-build. Verifying dependencies isn't something this code is responsible for. Typically `./configure` scripts are what validate dependencies, as dependencies may vary from version to version.
