### ISSUE TITLE
Specify default gem location

### ISSUE THREAD

**Issue by quintrino** [asdf-vm/asdf-ruby#111]
At the moment the `default-gems` file has to be stored in the $HOME directory. I'm wondering if it's possible to make this location customisable, either following the XDG format or via a custom enviroment variable such as ASDF_RUBY_DEFAULT_GEMS_PATH.

**Comment by rodjek** [comment]
@quintrino I've opened #114 with a change that might work for you. It's not completely configurable to allow arbitrary paths, but it means that as I store my asdf config at `$XDG_CONFIG_HOME/asdf-vm/asdfrc` I can now store my default gem list at `$XDG_CONFIG_HOME/asdf-vm/default-gems`

**Comment by quintrino** [comment]
Amazing. Thanks so much!

**Comment by quintrino** [comment]
Hmm, I just tested this by installing ruby 2.5.1 and then running ASDF_RUBY_VERSION=2.5.1 pry and it didn't seem to work. 

Are there steps you'd recommend for me to try and better understand why it doesn't install the default gems list?

**Comment by quintrino** [comment]
Hi @rodjek just checking if you're planning on merging in #114 ?

**Comment by rodjek** [comment]
@quintrino I don't have merge rights on the project

**Comment by quintrino** [comment]
@Stratus3D just wanted to check if you'd consider merging #114 ?

**Comment by Stratus3D** [comment]
Sorry for the late reply here 😆 . I think this has been solved by #212
