### ISSUE TITLE
Install errors for eventmachine

### ISSUE THREAD

**Issue by HashNuke** [asdf-vm/asdf-ruby#12]
Errors when installing eventmachine.

James has a modified ruby config to fix this https://twitter.com/JEG2/status/741806596108357632

I've come across this sometime in the past on my work machine (will need to get to the office to try and reproduce this with a new Ruby install).

In the meantime, I looked into the config options for Ruby using `./configure --help`. Will need to use `--with-opt-dir` like James' config.

```
./configure --help | grep with
  --disable-option-checking  ignore unrecognized --enable/--with options
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --with-baseruby=RUBY    use RUBY as baseruby; RUBY is the pathname of ruby
  --without-gcc           never use gcc
  --with-os-version-style=TYPE
  --with-arch=ARCHS       build an Apple/NeXT Multi Architecture Binary (MAB);
  --with-newlib           uses newlib version of NativeClient SDK
  --with-opt-dir=DIR-LIST add optional headers and libraries directories
  --with-winnt-ver=0xXXXX target Windows NT version (default to 0x0501)
  --without-gmp           disable GNU GMP to accelerate Bignum operations
  --with-jemalloc         use jemalloc allocator
  --with-dln-a-out        use dln_a_out if possible
  --without-valgrind      disable valgrind memcheck support
  --with-ext=EXTS         pass to --with-ext option of extmk.rb
  --with-out-ext=EXTS     pass to --without-ext option of extmk.rb
  --with-static-linked-ext
  --with-setup=SETUP      use extension libraries setup
  --with-rubylibprefix=DIR
  --with-soname=SONAME    base name of shared library
  --with-setjmp-type      select setjmp type
  --with-rubyarchprefix=DIR
  --with-rubysitearchprefix=DIR
  --with-ridir=DIR        ri documentation [[DATAROOTDIR/ri]]
  --with-ruby-version=STR ruby version string for version specific directories
  --with-sitedir=DIR      site libraries in DIR [[RUBY_LIB_PREFIX/site_ruby]],
  --with-sitearchdir=DIR  architecture dependent site libraries in DIR
  --with-vendordir=DIR    vendor libraries in DIR
  --with-vendorarchdir=DIR
  --with-search-path=DIR  specify the additional search path
  --with-rubyhdrdir=DIR   core headers in DIR
  --with-rubyarchhdrdir=DIR
  --with-sitehdrdir=DIR   core site headers in DIR [[RUBYHDRDIR/site_ruby]]
  --with-sitearchhdrdir=DIR
  --with-vendorhdrdir=DIR core vendor headers in DIR
  --with-vendorarchhdrdir=DIR
  --with-mantype=TYPE     specify man page type; TYPE is one of man and doc
  --with-ruby-pc=FILENAME pc file basename
  --with-destdir=DESTDIR  specify default directory to install
it to find libraries and programs with nonstandard names/locations.
```

Looks like there's no `--with-libyaml-dir`, `--with-readline-dir` and such. I don't remember where I picked this up from.

**Comment by HashNuke** [comment]
The above output was from ruby `2.3.1`.

Checked configure options in two different lines of Ruby `1.9.3-p551` and `2.1.5`. Both don't have `--with-openssl-dir` options and lots of internet literature seems to mention these.

**Comment by HashNuke** [comment]
Found it. These options names are not hard-coded anywhere. It's dynamic.
This is the code for `2.3.0` https://github.com/ruby/ruby/blob/v2_3_1/lib/mkmf.rb#L1731. The same is available in `1.9.3-p551` too (just diff line numbers).

So `--with-XYZ-dir` is the same as pass a list of paths with `--with-opt-dir`. Looks like eventmachine install issue doesn't pertain to paths.

**Comment by dpritchett** [comment]
Just trying asdf-ruby out and failing to get eventmachine on Ruby 2.2 here.  James's config isn't helping - I guess this is still a mystery?

That `/usr/local/opt/openssl` from James matches the path I get from `brew info openssl`.

**Comment by dpritchett** [comment]
Per this comment I've just bumped my `Gemfile` from `eventmachine` 1.0.8 to`eventmachine` 1.0.9 and things seem better 😕 

https://github.com/eventmachine/eventmachine/issues/643#issuecomment-171220005

**Comment by Stratus3D** [comment]
Closing since this doesn't seem to be an issue anymore.
