### ISSUE TITLE
Option to keep ruby sources after installation

### ISSUE THREAD

**Issue by sriedel** [asdf-vm/asdf-ruby#122]
I frequently browse the ruby sources when trying to figure out internals or just to check how certain things are implemented. Having all the sources of the ruby versions easily at hand under $MY_RUBY_HOME in rvm was a very welcome feature.

Could we get an option for asdf-ruby to store the sources from which ruby was installed instead of unconditionally deleting them after installation?

**Comment by Stratus3D** [comment]
This is now supported in asdf. See https://github.com/asdf-vm/asdf/issues/552 and asdf documentation for details.
