### ISSUE TITLE
"No version set for command bundle" when trying to add Ruby 2.5.5 to my toolchest

### ISSUE THREAD

**Issue by cobbr2** [asdf-vm/asdf-ruby#127]
I've tried this several times, so my guess is that there's something I'm just doing wrong, but: I install ruby-2.5.5, update my .tool-versions. `ruby --version` finds the right Ruby.  But `bundle` can't be found. Reshim doesn't work.  Ubuntu 18.04, asdf version 0.7.3:
```
rcobb@rcobb-t480:~/warehouse$ bundle --version
asdf: No version set for command bundle
you might want to add one of the following in your .tool-versions file:

ruby ruby-2.5.1
ruby 2.5.3
ruby 2.6.2
ruby 2.5.1
ruby 2.3.8
ruby ruby-2.3.8
ruby 2.3.4
rcobb@rcobb-t480:~/warehouse$ asdf uninstall ruby 2.5.5 && asdf install ruby 2.5.5
Downloading ruby-build...
...
Installing ruby-2.5.5...
Installed ruby-2.5.5 to /home/rcobb/.asdf/installs/ruby/2.5.5


rcobb@rcobb-t480:~/warehouse$ bundle --version
asdf: No version set for command bundle
you might want to add one of the following in your .tool-versions file:

ruby ruby-2.5.1
ruby 2.5.3
ruby 2.6.2
ruby 2.5.1
ruby 2.3.8
ruby ruby-2.3.8
ruby 2.3.4

rcobb@rcobb-t480:~/warehouse$ asdf reshim
rcobb@rcobb-t480:~/warehouse$ bundle --version
asdf: No version set for command bundle
you might want to add one of the following in your .tool-versions file:

ruby ruby-2.5.1
ruby 2.5.3
ruby 2.6.2
ruby 2.5.1
ruby 2.3.8
ruby ruby-2.3.8
ruby 2.3.4
rcobb@rcobb-t480:~/warehouse$ ruby --version
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
rcobb@rcobb-t480:~/warehouse$ asdf list ruby
  2.1.5
  2.3.4
  2.3.8
  2.5.1
  2.5.3
  2.5.5
  2.6.2
  ruby-2.3.8
rcobb@rcobb-t480:~/warehouse$ asdf --version
v0.7.3
```
Am I doing something wrong?  Thanks!

**Comment by cobbr2** [comment]
Yes. I'm failing to install bundler!

**Comment by betogrun** [comment]
I'm still facing this same error.
@cobbr2 did you manage to solve it?

**Comment by cobbr2** [comment]
I did... But I don't remember the answer today.

**Comment by betogrun** [comment]
No problems. @cobbr2 can you please reopen this issue?

**Comment by betogrun** [comment]
You are right @Stratus3D. 
Running `gem install bundler` solves the issue.
Thanks!

**Comment by ttilberg** [comment]
@Stratus3d Can you please review https://github.com/asdf-vm/asdf/issues/557#issuecomment-535503213 with that same mindset? I get something similar, but am trying to explicitly install things to the correct version. Do you feel this is the same, or a different bug? Any insight?

**Comment by Stratus3D** [comment]
Hi @ttilberg, I read your other comment, good description of the issue. You are right about that line being a magic comment in the shim. The shim was generated at a time in the past when only Python 3.6.8 offered the `ipython` executable on your system. Now you have Python 3.7.4 installed and the shim file hasn't been updated to reflect that. Typically `asdf reshim` will update your shims. Can you try that and see if it has any affect on the contents of your `ipython` shim file?

**Comment by ttilberg** [comment]
Thank you @Stratus3D. That fixed it. Sorry for turning this into a customer support thread.

**Comment by Stratus3D** [comment]
No worries @ttilberg

**Comment by kaka-ruto** [comment]
`gem install bundler` didn't work for me. 

But `gem update --system` did.

**Comment by Dwiga** [comment]
> `gem install bundler` didn't work for me.
> 
> But `gem update --system` did.

thanks dude

**Comment by doshinwills-okta** [comment]
> $ asdf global ruby <RUBY_VERSION>

Solved the issue for me

**Comment by WaismanDourado** [comment]
Thanks @doshinwills-okta  `asdf global ruby <RUBY_VERSION>` works for me!

**Comment by MTheProgrammer** [comment]
In my case reshim did not work. Moving project one directory up fixes the problem

**Comment by roberttravispierce** [comment]
For those still having this issue in a Rails project, try prefacing the rails command with `bundle exec...` (e.g. `bundle exec rails server`)

**Comment by grasbergerm** [comment]
I ran into this and just needed to do:
```
asdf uninstall ruby 3.4.9
asdf install ruby 3.4.9
```
