### ISSUE TITLE
java managed by asdf can not be found while installing jRuby

### ISSUE THREAD

**Issue by wbushey** [asdf-vm/asdf-ruby#131]
Hi, I'm having trouble installing jRuby via asdf. I have a project with the following `.tool-versions` file:

```
java adoptopenjdk-8.212
ruby jruby-9.1.13.0
```

The specified version of java is installed and shimmed:

```
~/Development/some_project  ➜ asdf list java
  adoptopenjdk-11.0.3
  adoptopenjdk-8.212
  oracle-8.141
~/Development/some_project ➜ asdf which java
/Users/bbushey/.asdf/installs/java/adoptopenjdk-8.212/bin/java
~/Development/some_project ➜ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)
```

But, when I attempt to install jRuby, I encounter a `asdf: No version set for command java` error.

Here is the log from my last attempt to install jRuby:

```
/var/folders/7f/zblpz7r53kgcfljp537bvs98xvxffv/T/ruby-build.20190828080500.84494 ~/Development/some_project
HTTP/1.1 200 OK
Content-Type: binary/octet-stream
Content-Length: 20993456
Connection: keep-alive
Date: Wed, 28 Aug 2019 12:36:39 GMT
Last-Modified: Wed, 06 Sep 2017 22:57:12 GMT
ETag: "6c642c8a2653a585779f453d8c843fd7"
Accept-Ranges: bytes
Server: AmazonS3
Age: 1703
X-Cache: Hit from cloudfront
Via: 1.1 e7d0317d0bc6b15fd0158376ae9d8bfc.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: MSP50-C1
X-Amz-Cf-Id: 9F9DUccIT53q4ZMoL4XMJSfEttaSQW2sb2QMDbS8UN79ngJuWqULSQ==

/var/folders/7f/zblpz7r53kgcfljp537bvs98xvxffv/T/ruby-build.20190828080500.84494/jruby-9.1.13.0 /var/folders/7f/zblpz7r53kgcfljp537bvs98xvxffv/T/ruby-build.20190828080500.84494 ~/Development/some_project
asdf: No version set for command java
you might want to add one of the following in your .tool-versions file:

java adoptopenjdk-8.212
java oracle-8.141
```

This is on MacOS Mojave (10.14.6), with asdf v0.7.4 and the latest versions of asdf-ruby and asdf-java.

Does anybody have advice on what might be causing ruby-build to not be able to find `java`?

**Comment by Stratus3D** [comment]
Does it succeed if you run `asdf reshim` and then try installing ruby? Not really sure what is going on, but my guess is either the shims aren't in place during the ruby build, or they do exist and aren't invoking the actual java executables.

**Comment by wbushey** [comment]
Hi @Stratus3D, unfortunately no, reshimming doesn't fix the problem. I've attempted to reshim everything `asdf reshim`, as well as reshim just the relevant version of java `asdf reshim java adoptopenjdk-8.212`. In both cases, I still receive the same `No version set for command java`.

**Comment by wbushey** [comment]
I've dug a little deeper into this issue, and it's become clear that this isn't really an `asdf-ruby` issue. `ruby-build` fails with the same error if I execute that manually. Given that, I'm going to close this issue

**Comment by wbushey** [comment]
OK, I did eventually track down the cause of this issue, and may have found a bug.

My project included the following `.tool-versions`
```
java adoptopenjdk-8.212
ruby jruby-9.1.13.0
```

But, I was also defining some global versions in a `.tool-versions` in my home directory, that included
```
java adoptopenjdk-11.0.3
```

At some point, my installation of `adoptopenjdk-11.0.3` was deleted, but the (empty) folder still existed in `~/.asdf/installs`. So, attempts to use `java` outside of my project would attempt to use a java that didn't actually exist. Hence the `asdf: No version set for command java` error. Once I sent java in my home folder's `.tool-versions` to be a version that I had a working installation for, I was successfully able to install jruby!

This does suggest that, if somebody specifies versions of both java and (j)ruby in a project's `.tool-versions`, then a version of java other than the one specified in that project might be used to install (j)ruby. If that's the case, I think that most people would not expect that behavior - it was definitely unexpected for me. Does this sound like a possible bug to you @Stratus3D ?

**Comment by Stratus3D** [comment]
It's possible that is a bug. If it's something you can reproduce with the `.tool-versions` file you posted and reshimming manually does not fix the issue (`asdf reshim`), then I'd say yes. It's quite possible we aren't reshimming between installations properly. Let me know and we can reopen this issue.
