### ISSUE TITLE
Dealing with different name conventions from legacy file

### ISSUE THREAD

**Issue by simonc** [asdf-vm/asdf-ruby#14]
Hi,

I recently switched to asdf but I'm facing small issues when working with other teams.

The way Ruby is installed with asdf, when the legacy file contains `2.3.1` it works but when it contains `ruby-2.3.1` it doesn't.

Do you think there is a way to make asdf accept both?

Thanks.

**Comment by simonc** [comment]
In the meantime, creating a symlink `ruby-2.3.1 -> 2.3.1` seems to work.

**Comment by Stratus3D** [comment]
@simonc can you test this with the latest versions of asdf and asdf-ruby? I'm fairly certain this was fixed a while ago. Please reopen if you encounter any issues.

**Comment by simonc** [comment]
It seems to be working now. Thanks :wink:
