### ISSUE TITLE
How can I apply patch?

### ISSUE THREAD

**Issue by tejanium** [asdf-vm/asdf-ruby#15]
I'm trying to install older versions of Ruby, but there is widely known ssl bug when compile, with rvm or rbenv, this can be solved by passing argument --patch when installing.

How can I do this with asdf-ruby?

**Comment by belaustegui** [comment]
I am also interested on this, since I'm having problems installing Ruby 2.2.3 on Ubuntu 16.04 because of openSSL. To solve it I need to compile Ruby with a specific patch.

**Comment by HashNuke** [comment]
There's no support for patches right now. Marking this ticket as help-wanted incase someone wants to take a look.

**Comment by hubertlepicki** [comment]
What would be the command format you want? I have hardcoded applying patch for myself (had to install very old Ruby on new system, openssl compiled without v3). I can quickly fix it up for you and send a pull request.

**Comment by paulodiovani** [comment]
+1 to this
