### ISSUE TITLE
Problem with versions on macOS

### ISSUE THREAD

**Issue by gheorghitahurmuz** [asdf-vm/asdf-ruby#158]
Hi, I have the next situation and I didn't find any solution:

<img width="832" alt="Screenshot 2020-03-26 22 11 16" src="https://user-images.githubusercontent.com/12661929/77692143-c64ab980-6fae-11ea-887f-47fdbdca4dae.png">

**Comment by Stratus3D** [comment]
What happens if you run `asdf current`? Does it output `ruby 2.6.3`?

**Comment by gheorghitahurmuz** [comment]
Yes,

`ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]`

**Comment by gheorghitahurmuz** [comment]
I tried with `asdf exec bundle install` and everything it's ok now.

**Comment by Stratus3D** [comment]
You might try running `type -a bundle` to see if you have any old `bundle`s on your PATH.

**Comment by gheorghitahurmuz** [comment]
``` type -a bundler
bundler is /Users/gheorghitahurmuz/.asdf/shims/bundler
bundler is /usr/bin/bundler
```
