### ISSUE TITLE
What's the best way to add new ruby versions? Specifically 2.6.6 and 2.7.1

### ISSUE THREAD

**Issue by weilandia** [asdf-vm/asdf-ruby#160]

**Comment by Stratus3D** [comment]
If you've already got the plugin installed and don't see the latest Rubies, try running `asdf plugin-update ruby` to update the plugin. If you still do not see the latest versions available check out the [latest ruby-build releases](https://github.com/rbenv/ruby-build/releases) and see if there is a recent one that adds the versions you are looking for. asdf-ruby uses ruby-build for fetching and installing of Ruby versions.

**Comment by weilandia** [comment]
Thanks @Stratus3D !
