### ISSUE TITLE
bundle-audit check fails

### ISSUE THREAD

**Issue by tleish** [asdf-vm/asdf-ruby#164]
I receive the following message when attempting to run [bundler-audit gem](https://github.com/rubysec/bundler-audit).

```
$ bundle-audit check
asdf: No preset version installed for command bundle-audit
Please install the missing version by running one of the following:

asdf install ruby 2.6.5

or add one of the following in your .tool-versions file:

ruby 2.4.3
```

Current settings:
```
$ asdf current
ruby           2.6.5    (set by ~/src/.tool-versions)
```

My .tool-versions file in the same directory
```
$ cat .tool-versions
ruby 2.6.5
```

If I run other `bundle exec` commands, they execute just fine using ruby 2.6.5.

I know this worked at one time.  What do I need to change/fix in order to run `bundle audit`

**Comment by Stratus3D** [comment]
Did you try running `asdf reshim` after installing `bundler-audit`?

**Comment by Stratus3D** [comment]
Closing due to lack of a response.
