### ISSUE TITLE
ASDF dont install ruby 2.7.1 or 2.7.0

### ISSUE THREAD

**Issue by edersonferreira** [asdf-vm/asdf-ruby#167]
Hello.
I am trying to install ruby with ASDF with the command

`asdf install ruby 2.7.1`

but when i use this, open an error, this is the error:

```
Downloading ruby-2.7.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.bz2
Installing ruby-2.7.1...

BUILD FAILED (LinuxMint 19.3 using ruby-build 20200401)

Inspect or clean up the working tree at /tmp/ruby-build.20200428214035.30567.E3NgUV
Results logged to /tmp/ruby-build.20200428214035.30567.log

Last 10 log lines:
	from ./tool/rbinstall.rb:279:in `open_for_install'
	from ./tool/rbinstall.rb:845:in `block in install_default_gem'
	from ./tool/rbinstall.rb:835:in `each'
	from ./tool/rbinstall.rb:835:in `install_default_gem'
	from ./tool/rbinstall.rb:799:in `block in <main>'
	from ./tool/rbinstall.rb:950:in `block in <main>'
	from ./tool/rbinstall.rb:947:in `each'
	from ./tool/rbinstall.rb:947:in `<main>'
uncommon.mk:373: recipe for target 'do-install-all' failed
make: *** [do-install-all] Error 1
```

What i do now?

Thanks for read this.

**Comment by Stratus3D** [comment]
Can you share the contents of `/tmp/ruby-build.20200428214035.30567.log` if it still exists?

**Comment by edersonferreira** [comment]
Hello, i solved the problem.

I miss to install this packets
`sudo apt install git automake autoconf libreadline-dev libncurses-dev libssl-dev libyaml-dev libxslt-dev libffi-dev libtool unixodbc-dev unzip curl zlib1g-dev sqlite3 libsqlite3-dev`

now i can install ruby on ASDF.

**Comment by renatamarques97** [comment]
@edersonferreira ruby 2.7.1 doesn't appear for me using `asdf list all ruby` ( #168 ), how can I install this version?

**Comment by Stratus3D** [comment]
@renatamarques97 have you tried updating asdf-ruby? `asdf plugin-update ruby`.

**Comment by edersonferreira** [comment]
@renatamarques97 try to install ruby with `asdf install ruby 2.7.1 && asdf global ruby 2.7.1`
i dont know why this not appear, try update and upgrade your system.
