### ISSUE TITLE
ruby 2.7.1 not available to install

### ISSUE THREAD

**Issue by renatamarques97** [asdf-vm/asdf-ruby#168]
```shell
asdf list all ruby
```

![Screen Shot 2020-05-04 at 10 49 12](https://user-images.githubusercontent.com/25162312/80972948-1eb67780-8df5-11ea-8cf2-ee8c0448f72d.png)

**Comment by Stratus3D** [comment]
I see:

```
2.6.5
2.6.6
2.7.0-dev
2.7.0-preview1
2.7.0-preview2
2.7.0-preview3
2.7.0-rc1
2.7.0-rc2
2.7.0
2.7.1
2.8.0-dev
jruby-1.5.6
jruby-1.6.3
```

**Comment by edersonferreira** [comment]
Try to update your system, if is a debian or debian based, use
`sudo apt update && sudo apt upgrade`
 and use
`asdf plugin-update ruby`

**Comment by renatamarques97** [comment]
@edersonferreira thanks for this, solved my problem.
