### ISSUE TITLE
asdf: No preset version installed for command solargraph

### ISSUE THREAD

**Issue by kaka-ruto** [asdf-vm/asdf-ruby#173]
I had an issue with my Ruby installation using asdf-ruby. So I deleted that installation (Ruby 2.5.1) and reinstalled it.

I also uninstalled all Solargraph gems just incase they were pointing to an old Ruby installation path, and did another gem install solargraph

solargraph -v or opening a Ruby file in Vim throws an error

```
asdf: No preset version installed for command solargraph
Please install the missing version by running one of the following:

asdf install ruby 2.5.1
```

![Screen Shot 2020-06-25 at 14 18 39](https://user-images.githubusercontent.com/16320124/85712046-949dd780-b6f0-11ea-8c73-09aba68404fe.png)

**Comment by Stratus3D** [comment]
What happens when you run `asdf reshim`? Does that fix the problem? And what does `asdf which solargraph` output?

**Comment by kaka-ruto** [comment]
`asdf reshim` runs without any error, but the problem persists.

`asdf which solargraph` brings up the same error as above - No preset version installed for command solargraph

**Comment by Stratus3D** [comment]
What version of asdf are you running?

**Comment by kaka-ruto** [comment]
I am running `v0.7.8-4a3e3d6`

**Comment by Stratus3D** [comment]
I may be wrong, but this might be fixed by running `gem install solargraph` or `bundle install`. I think that error message might get printed when a command is available in another version of Ruby, but not in the current version you have selected (`2.5.1`). We've updated the messages like these that asdf prints to make things clearer. They will be present in asdf 0.8.0 when it is released.

**Comment by kaka-ruto** [comment]
Thanks @Stratus3D . I do have solargraph available for other Ruby versions. But somehow not available for 2.5.1

I have also run `gem install solargraph`, then `asdf reshim`. 

`asdf which solargraph` throws the same error above. Or could it be an issue with 2.5.1? I have reinstalled it twice but still not finding solargraph.

**Comment by Stratus3D** [comment]
Odd. What you described sounds familiar, but typically `asdf reshim; gem install <gem name>` usually fixes it. Not sure what is going on. Are you sure the `gem` executable you ran was for 2.5.1? It should be, but just to check run `asdf which gem` and see if it points to the 2.5.1 version of gem.

**Comment by kaka-ruto** [comment]
Funny as it does. `asdf which gem` points to `/Users/kaka/.asdf/installs/ruby/2.5.1/bin/gem`

**Comment by Stratus3D** [comment]
Odd. I'm not sure what is going on then.

**Comment by kaka-ruto** [comment]
I did not succeed in this. What I ended up doing is to point `solargraph` to another installation of Ruby.

I am using `coc-solargraph` in Vim, so this is what I did `"solargraph.commandPath": "/Users/kaka/.asdf/installs/ruby/2.6.5/bin/solargraph"`. 

The downside of this is that I am using the formatting, documentation, etc, of Ruby 2.6.5 in every Ruby project, regardless of what Ruby version that project uses.

**Comment by kaka-ruto** [comment]
Alright, alright. So after hours and hours of debugging, I finally found the problem.

I am using Tmuxinator to manage my Tmux sessions, and apparently the brew installation of tmuxinator takes over the Ruby executable directory when you start a Tmux session. Meaning when I installed solargraph, it was installed into the Tmuxinator executable directory, hence my Local Ruby was not finding it.

I solved this by `brew uninstall tmuxinator` and using `gem install tmuxinator` instead.

I then ran `gem install solargraph` and now `solargraph -v` works!!!

PS: I believe the tmuxinator behaviour is a bug and I have raised a bug report here - https://github.com/tmuxinator/tmuxinator/issues/780

Closing this.

**Comment by Stratus3D** [comment]
Good find! I also recall having issues several years ago when I started using tmuxinator, but I looked at my dotfiles and it didn't look like I made any config changes to get things working. I am using gem installed tmuxinator.

**Comment by kaka-ruto** [comment]
I also resorted to using the tmuxinator gem. Much easy to work with.

**Comment by kaka-ruto** [comment]
Now that I am using the gem version, this was helpful! http://stratus3d.com/blog/2017/10/01/asdf-tip-global-programs/

Thanks @Stratus3D 😸

**Comment by kaka-ruto** [comment]
Hmm, only that it sets the ASDF_RUBY_VERSION env variable everywhere, therefore setting Ruby to that version everywhere. Looks like I have to unset this as well?

There a way i can specify the Ruby version only for the tmuxinator alias and not globally?

**Comment by Stratus3D** [comment]
You can always run commands in a subshell: `$(asdf shell ruby 2.6.5; tmuxinator)`. However, note this still affects everything that is run inside the subshell, so anything started by tmuxinator would inherit ruby 2.6.5.

Right now I just have tmuxinator installed for the global version of ruby that is set in my home directory, and then I only run `tmuxinator` from the home directory or other subdirectories that do not have another ruby version set. That gets around the problem easy enough. Alternatively you could unset the ruby version inside tmuxinator (I think it has a `pre` callback you could use).

**Comment by kaka-ruto** [comment]
I have gone with your current approach. Have tmuxinator installed for one ruby version and just use tmuxinator on a dir with that ruby version, fair enough. Thanks again Trevor
