### ISSUE TITLE
usr/bin executables are overriding Gems path

### ISSUE THREAD

**Issue by jlurena** [asdf-vm/asdf-ruby#186]
Everytime I run `bundler` I get the version in `/usr/bin`

ie:

```
$ which bundler
/user/bin/bundler
```

This is very strange but it seems I need to call the Gem itself for it to be initialized.

Doing the following **once** fixes it

```
eval $(which bundle)
```

ASDF Version: v0.8.0
MacOS:  10.15.7
Ruby: 2.3.6

**Comment by Stratus3D** [comment]
Sorry for the late reply here. This shouldn't be a problem if you've properly installed asdf. After installing asdf install this plugin, install a version of ruby with it, then use `gem` to install bundler, and then run `asdf reshim` for good measure. `type -a bundler` should output the path to the asdf shim for bundler.

**Comment by Stratus3D** [comment]
Closing as no other users have reported this issue.
