### ISSUE TITLE
Is it possible to enable doc installation?

### ISSUE THREAD

**Issue by pootsbook** [asdf-vm/asdf-ruby#19]
This [line](https://github.com/asdf-vm/asdf-ruby/blob/806af1b699dccda7c97dec32940ef8574ee890bb/bin/install#L121) would seem to suggest that `--disable-install-doc` is hard coded:

```
configure_options="$configure_options --enable-shared --disable-install-doc"
```

Is there a way to allow documentation to be installed?

Use-case: people (like me) who use `ri` extensively.

**Comment by HashNuke** [comment]
@pootsbook Set the env var `RUBY_EXTRA_CONFIGURE_OPTIONS` when installing rubies.

```
RUBY_EXTRA_CONFIGURE_OPTIONS="--enable-shared --disable-install-doc" asdf install ruby 3.2.1
```

Closing the issue. Please let me know if there's trouble running that.

**Comment by pootsbook** [comment]
@HashNuke running that installs Ruby fine, but it still disables the installation of docs. I think what I am looking for is a way to ___remove___ the option `--disable-install-doc` from the `configure_options` var but it is hard-coded.

The only way to do so would be to supply my own set of options via `RUBY_CONFIGURE_OPTIONS`, but going down that path loses all the `os_configure_options` which I would like to keep.

Do you think you would accept a PR that would either:

1. add a flag to enable and disable `--disable-install-doc` OR 
2. even remove this as a default, and then let people know if they ___don’t___ want docs that they can specify `RUBY_EXTRA_CONFIGURE_OPTIONS="--disable-install-doc"`? (This would mirror the behaviour of RubyGems, which installs `ri` and `rdoc` unless told not to via `--no-ri --no-rdoc`).

**Comment by webkay** [comment]
@HashNuke meant `--enable-install-doc` in place of `--disable-install-doc` when you say

> RUBY_EXTRA_CONFIGURE_OPTIONS="--enable-shared --disable-install-doc" asdf install ruby 3.2.1

right? I agree with you @pootsbook I think there are still many `ri` users out there. And personally I almost gave up before I found this issue.

**Comment by HashNuke** [comment]
Agree. Good idea to enable it by default.
