### ISSUE TITLE
Ruby can't load libraries installed with bundle install

### ISSUE THREAD

**Issue by cmcramer** [asdf-vm/asdf-ruby#194]
I'm running asdf v.0.8.0, installed via homebrew, on macOS Catalina (10.15.7) with the ruby plugin. 

Ruby versions change as expected globally and for different projects. Bundle install runs without errors and gems installed via bundler are located in the correct ruby version; e.g. `.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/`. However a `require` statement trying to load any gem installed by Bundler fails with `cannot load such file -- <gem_library>`. 

If gem is installed with `gem install <gem>` the `require` statements work.

**Comment by cmcramer** [comment]
I reinstalled asdf using git and have the same problem. 

This only seems to happen if the gem repo is specified in the Gemfile, as in this example:

Excerpt from Gemfile:
`gem 'pycall', git: 'https://github.com/mrkn/pycall.rb'`

Results from `bundle info pycall`
```
  * pycall (1.3.1 9a3d350)
	Summary: pycall
	Homepage: https://github.com/mrkn/pycall
	Path: /Users/xxx/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/pycall.rb-9a3d35024300
```

Attempts to require pycall return:
```
LoadError:
  cannot load such file -- pycall/import
```

---
It will load if installed manually using:
`gem install pycall`

Or the Gemfile doesn't specify git repo:
`gem pycall`

**Comment by cmcramer** [comment]
This is fixed by adding before git gems are required. 

```
require 'bundler/setup'
```

A nice feature would be for asdf-ruby to handle this automatically like rvm, to make it easier when working with developers that use rvm rather than asdf.

**Comment by Stratus3D** [comment]
I'm sorry using asdf-ruby was such a hassle. I'm pretty busy these days, but if you can provide any concrete suggests on what we need to change to make this better, and why they are needed, I may be able to improve this plugin.
