### ISSUE TITLE
Ruby 3.0

### ISSUE THREAD

**Issue by DevotionGeo** [asdf-vm/asdf-ruby#196]
Why isn't Ruby 3.0 there?

**Comment by andypearson** [comment]
This PR needs to be merged: https://github.com/asdf-vm/asdf-ruby/pull/192

For the moment you can do `ASDF_RUBY_BUILD_VERSION=v20201225 asdf install ruby 3.0.0` to get the new shiny Ruby :)

**Comment by Stratus3D** [comment]
#192 has been merged. Closing this ticket.

**Comment by pmukerji** [comment]
@Stratus3D - just a friendly ping that the issue is still open

**Comment by Stratus3D** [comment]
Thanks @pmukerji closing for real this time :laughing:

**Comment by DevotionGeo** [comment]
Thanks everyone!
