### ISSUE TITLE
Apple Silicon M1 ARM64 Native Info

### ISSUE THREAD

**Issue by fearoffish** [asdf-vm/asdf-ruby#198]
I had no end of trouble figuring out the exact configuration of ENV vars and tools to use for this, so I thought I'd just document it here for others. With this I have Ruby 2.6.3, 2.6.6 and 2.7.2 installed through asdf-ruby.

- Homebrew native installation (arm64)
- Homebrew packages: `libffi`, `libyaml`, `zlib`, `readline`
- ENV vars
  - `export RUBY_CONFIGURE_OPTS="--with-zlib-dir=/opt/homebrew/opt/zlib --with-openssl-dir=/opt/homebrew/opt/openssl@1.1 --with-readline-dir=/opt/homebrew/opt/readline --with-libyaml-dir=/opt/homebrew/opt/libyaml"`
  - `export RUBY_CFLAGS="-Wno-error=implicit-function-declaration"`

**Comment by fearoffish** [comment]
Closing as this is information only.

**Comment by Stratus3D** [comment]
Feel free to update the readme if you think it could be improved!

**Comment by ryanmtaylor-tunecore** [comment]
I'd just like to add that maybe a better more future-proof version of the `RUBY_CONFIGURE_OPTS` might be:

`export RUBY_CONFIGURE_OPTS="--with-zlib-dir=$(brew --prefix zlib) --with-openssl-dir=$(brew --prefix openssl@1.1) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml)"`

**Comment by mabid** [comment]
had the same issue this is what worked for me. had to add gdbm 
```export RUBY_CONFIGURE_OPTS="--with-zlib-dir=$(brew --prefix zlib) --with-openssl-dir=$(brew --prefix openssl@1.1) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --with-gdbm-dir=$(brew --prefix gdbm)"```

and export the following as well

``` export CFLAGS="-Wno-error=implicit-function-declaration"```

**Comment by pboling** [comment]
Ruby 2.6.10 will not install on Apple silicon + XCode 14 + MacOS Ventura, even with these settings, due to 
https://github.com/rbenv/ruby-build/discussions/2072, which is ultimately due to https://bugs.ruby-lang.org/issues/18912

It may work with Xcode 13.4, but you can't downgrade if you are already on MacOS Ventura.

**Comment by carflynn2009** [comment]
> All of the above as one block
> 
> ```shell
> brew install zlib readline libyaml libffi
> export RUBY_CONFIGURE_OPTS="--with-zlib-dir=$(brew --prefix zlib) --with-openssl-dir=$(brew --prefix openssl@1.1) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --with-gdbm-dir=$(brew --prefix gdbm)"
> export CFLAGS="-Wno-error=implicit-function-declaration"
> ```

I can confirm this now works for me running MacOS Sonoma 14.0
