### ISSUE TITLE
On Apple Silicon: ruby-build: definition not found: 3.0.0

### ISSUE THREAD

**Issue by mgmodell** [asdf-vm/asdf-ruby#200]
When I try to install the latest ruby (3.0.0) on my M1 Macbook Pro, it fails with:
`ruby-build: definition not found: 3.0.0`
Clearly, [ruby 3 has been released more than a month ago](https://www.ruby-lang.org/en/downloads/releases/), so either we're running into problems building/packaging it for Apple Silicon (M1) or no one's had the bandwidth to do so yet. Unfortunately, I'm not sure how best to engage with the community here. How would I follow up on the status of this? Is there a listing of current platforms and levels of support? How might I offer assistance if it is needed (and I'm able)?

**Comment by ashmckenzie** [comment]
Did you happen to try running `asdf plugin update ruby` beforehand?

**Comment by mgmodell** [comment]
I'm so sorry, @ashmckenzie , I actually got an answer that worked for me on [StackOverflow](https://stackoverflow.com/questions/65983389/on-apple-silicon-ruby-build-definition-not-found-3-0-0/65985896#65985896): I ran `brew update && brew upgrade rbenv ruby-build ` and now it works. I didn't realise that I needed ruby-build, but now I seem to be OK. Thanks!

**Comment by Stratus3D** [comment]
@mgmodell that should have any affect on the version of ruby-build that asdf-ruby uses. It downloads and uses its own version.

**Comment by mgmodell** [comment]
Hmmm... that's what I did and it resolved the issue. I'd previously run `asdf update`, but not `asdf plugin update ruby`. @Stratus3D, would you like me to uninstall the ruby and rbenv and ruby-build and give `asdf plugin update ruby` a try to verify?

**Comment by Stratus3D** [comment]
If you don't mind going through that hassle, yes please. If my assumptions here are wrong I've got some things I need to fix.

**Comment by mgmodell** [comment]
OK. I uninstalled all rubies and ruby-build (never had rbenv) and then I went ahead and ran `asdf install ruby 3.0.0` and it seems to have worked. Minimal testing, but it seems OK.

**Comment by Stratus3D** [comment]
Thanks @mgmodell, that is what I was hoping. Glad it worked!
