### ISSUE TITLE
Any chance of getting 2.7.2?

### ISSUE THREAD

**Issue by joshchernoff** [asdf-vm/asdf-ruby#207]
Looks like we are missing a patch from last october.

**Comment by Stratus3D** [comment]
Running `asdf list all ruby` I see ruby 2.7.2 in the list. Perhaps you need to update to the latest version of this plugin? `asdf plugin update ruby`.

**Comment by pboling** [comment]
@Stratus3D If you see it you may have the master hack setup to be applied transparently.  I had to use the master hack to get 2.7.2 across all our engineers machines.

**Comment by pboling** [comment]
Ref: https://github.com/asdf-vm/asdf-ruby/issues/204#issuecomment-803360500

**Comment by joshchernoff** [comment]
No, I'm just dumb and only ran `asdf update` thinking it updated the ruby list too. 🤦‍♂️

**Comment by Stratus3D** [comment]
@pboling I'm not sure what you mean by master branch hack, but I didn't do anything other than install asdf-ruby and update it to the latest version. `asdf plugin update ruby`. No hacks should be necessary, just update this plugin to latest.

**Comment by pboling** [comment]
@Stratus3D This is the `master` hack:
```
ASDF_RUBY_BUILD_VERSION=master asdf install ruby 2.7.2
```
And it was required, until recently.

**Comment by Stratus3D** [comment]
Yes, I know I've had access to Ruby 2.7.2 via this plugin since November, so it's been a while.

**Comment by seivan** [comment]
> @pboling I'm not sure what you mean by master branch hack, but I didn't do anything other than install asdf-ruby and update it to the latest version. `asdf plugin update ruby`. No hacks should be necessary, just update this plugin to latest.

That's only true if `asdf plugin update` will reset the plugin staging and remove files under `.gitignore`? 
Otherwise you have to override the setting like @pboling did. I see that `ruby-build` is under [.gitignore](https://github.com/asdf-vm/asdf-ruby/blob/master/.gitignore)

But none of these commands from `asdf` will actually remove `ruby-build`
```shell
(cd "$plugin_path" && git fetch -p -u origin "$gitref:$gitref" && git checkout -f "$gitref")
```


Which means that you actually have to trigger it via something like
`ASDF_RUBY_BUILD_VERSION=v1.1.1 asdf list all ruby`

At least that's how I designed it in my fork. But I would wish for it to be automatic. 
Maybe I'm wrong and the git fetch and checkouts will trigger the `.gitignore` to remove the files, but I doubt it.

**Comment by Stratus3D** [comment]
I'm not sure what you mean @seivan , but your conclusion is wrong. Anytime we change the ruby-build version contained in this plugin's `lib/utils.sh` file, the existing `ruby-build` binary will be deleted and replaced with a new `ruby-build`. See https://github.com/asdf-vm/asdf-ruby/blob/master/lib/utils.sh#L24

**Comment by seivan** [comment]
> I'm not sure what you mean @seivan , but your conclusion is wrong. Anytime we change the ruby-build version contained in this plugin's `lib/utils.sh` file, the existing `ruby-build` binary will be deleted and replaced with a new `ruby-build`. See https://github.com/asdf-vm/asdf-ruby/blob/master/lib/utils.sh#L24

Yep you're correct, I changed my fork **not** to do that. 
Instead it only upgrades when it's missing **OR** opt in by the user to use a different version themselves.  

Upgrading a plugin should remove it by using the `.gitignore` to reset instead. 
If updating a plugin would remove it, it would resort to the default version designated.

**Comment by Stratus3D** [comment]
> Upgrading a plugin should remove it by using the .gitignore to reset instead.
> If updating a plugin would remove it, it would resort to the default version designated.

I don't undestand what you are saying, but we already have `ruby-build` in the `.gitignore` and everything works correct (in this repo at least).

**Comment by seivan** [comment]
@Stratus3D I am saying that it would be better to let asdf reset on plugin updates and remove everything defined in `.gitignore` on updates.
This also means that  you don't have to check `if [ "$current_ruby_build_version" != "$RUBY_BUILD_VERSION" ];` each time.

Only check when the dependency is missing **OR** when the user supplies their own version.

**Comment by Stratus3D** [comment]
That wouldn't improve anything. And there is no reason to delete files that may be needed after an update. Just because we make a change to this plugin's code doesn't mean we want to change the `ruby-build` version, so deleting and re-downloading would be a waste. What we have is more efficient.

**Comment by pboling** [comment]
I don't understand what happened for me then.

I am on the standard plugin, and I had to use the `ASDF_RUBY_BUILD_VERSION` hack on Feb 12, 2021, Feb 17, 2021, and Feb 25, 2021.  I _think_ I updated the plugin first... I think I sent so far as to reinstall `asdf` completely, and not even that helped.

In any case, sounds like it should be working as expected now.  Thanks!

**Comment by Stratus3D** [comment]
@pboling if you encounter this issue again please let me know. It's possible there is something that doesn't work properly on all operating systems/environments, but I've not encountered it on my OSX and Ubuntu computers.
