### ISSUE TITLE
Big Sur / M1: Multiple versions fail with "machine `arm64-apple` not recognised"

### ISSUE THREAD

**Issue by iftheshoefritz** [asdf-vm/asdf-ruby#210]
I'm on an M1 MBP 13". All the Ruby versions I've tried except v3 have failed to install:

```
~  asdf install ruby 2.6.5
Downloading openssl-1.1.1j.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/aaf2fcb575cdf6491b98ab4829abf78a3dec8402b8b81efc8f23c00d443981bf
Installing openssl-1.1.1j...
Installed openssl-1.1.1j to /Users/fm/.asdf/installs/ruby/2.6.5

Downloading ruby-2.6.5.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.5.tar.bz2
Installing ruby-2.6.5...
ruby-build: using readline from homebrew

BUILD FAILED (macOS 11.2.3 using ruby-build 20210405)

Inspect or clean up the working tree at /var/folders/_m/8mld51pj7tn48mztkc9j3p3c0000gn/T/ruby-build.20210414142348.38483.WVGX2Y
Results logged to /var/folders/_m/8mld51pj7tn48mztkc9j3p3c0000gn/T/ruby-build.20210414142348.38483.log

Last 10 log lines:
/Users/fm/.asdf/installs/ruby/2.6.5/openssl/share/doc/openssl/html/man7/X448.html -> /Users/fm/.asdf/installs/ruby/2.6.5/openssl/share/doc/openssl/html/man7/X25519.html
/Users/fm/.asdf/installs/ruby/2.6.5/openssl/share/doc/openssl/html/man7/x509.html
/var/folders/_m/8mld51pj7tn48mztkc9j3p3c0000gn/T/ruby-build.20210414142348.38483.WVGX2Y ~
~
/var/folders/_m/8mld51pj7tn48mztkc9j3p3c0000gn/T/ruby-build.20210414142348.38483.WVGX2Y ~
/var/folders/_m/8mld51pj7tn48mztkc9j3p3c0000gn/T/ruby-build.20210414142348.38483.WVGX2Y/ruby-2.6.5 /var/folders/_m/8mld51pj7tn48mztkc9j3p3c0000gn/T/ruby-build.20210414142348.38483.WVGX2Y ~
checking for ruby... /Users/fm/.asdf/shims/ruby
checking build system type... Invalid configuration `arm64-apple-darwin20.3.0': machine `arm64-apple' not recognized
configure: error: /bin/sh tool/config.sub arm64-apple-darwin20.3.0 failed
make: *** No targets specified and no makefile found.  Stop.
```

Same error with 2.6.3, 2.6.5, 2.7.1, 2.7.2.

But with 3.0.0:

```
☁  ~  asdf install ruby 3.0.0
Downloading openssl-1.1.1j.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/aaf2fcb575cdf6491b98ab4829abf78a3dec8402b8b81efc8f23c00d443981bf
Installing openssl-1.1.1j...
Installed openssl-1.1.1j to /Users/fm/.asdf/installs/ruby/3.0.0

Downloading ruby-3.0.0.tar.gz...
-> https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0.tar.gz
Installing ruby-3.0.0...
ruby-build: using readline from homebrew
Installed ruby-3.0.0 to /Users/fm/.asdf/installs/ruby/3.0.0

☁  ~  asdf list ruby
  3.0.0
☁  ~  asdf global ruby 3.0.0
☁  ~  ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]
```

Why is only 3.0.0 succeeding?

**Comment by iftheshoefritz** [comment]
The answer is that all the versions that failed are old versions of their respective Ruby families and the build includes an old `tools/config.sub` which does not know about `arm64-apple...`. Later versions, (e.g. 2.7.3, 2.6.7) build with an updated config.sub.

If I build these older versions from source I can copy in a config.sub from the source of a newer version and the build succeeds.

I am interested in whether it is possible to override what `config.sub` file gets used by configure with a command line option?

**Comment by iftheshoefritz** [comment]
Update: it is possible to override the result of config.sub by passing `CONFIGURE_OPTS="--build aarch64-apple-darwin20"` to ruby-build. In this case, `aarch64-apple-darwin20` is the result of the config.sub included with the Ruby 3 source.

**Comment by noraj** [comment]
Even if you are able to build the desired ruby version with a M1-based CPU chances are building native-gems will fails too and more generally speaking any dependencies with other languages (nodejs, python, etc.) that has C binding, because ARM architecture is not as well supported as x86 in application development environments.

**Comment by iftheshoefritz** [comment]
Actually none of my colleagues on m1 are reporting any problems like this, despite installing the exact same things. It is infuriating, I can't work out what the difference between my massive and theirs is.

**Comment by iftheshoefritz** [comment]
@noraj  you're right, native gems fail installation, but there is an easy fix in all of the cases that I've encountered for those. This problem I'm reporting here affects only me in my office, and apparently only the two other people on the entire Internet who have liked my solution.

**Comment by airtonix** [comment]
@iftheshoefritz don't use an M1 then ?

**Comment by noraj** [comment]
@iftheshoefritz I had to help someone with a M1 mac but asdf-ruby was only one of the many problems. Another problem due to the ARM architecture is virtualization. And even problems with all macs (arm and x86) is due to the fact that macos is using bash 3.2 while many bash script expect you to have a least bash 4.0. macs are more suited for VIPs than power user. I'd suggest having a Dell, Lenovo or HP for a pro laptop and then whatever Linux distribution or even windows rather than a mac if you are a power user. But that's totally off-topic.

**Comment by iftheshoefritz** [comment]
@airtonix what a bizarre comment. I'm not complaining about using M1, I'm ecstatic with it.

**Comment by airtonix** [comment]
> @airtonix what a bizarre comment. I'm not complaining about using M1, I'm ecstatic with it.

Not bizare at all tbh.

if you're wasting days and days because: "M1", then don't waste days and days by removing the problem.

**Comment by iftheshoefritz** [comment]
Closing this. I'm not on top of the problem anymore but since 2.7 has reached eol and newer versions of ruby do install without problems, it seems obsolete.

**Comment by Stratus3D** [comment]
For anyone else experiencing similar issues, please see the ruby-build project specifically, and open any issues there if necessary. As @SeanSith pointed out asdf-ruby uses ruby-build for everything, so we can only provide version/architecture combos supported by ruby-build itself.
