### ISSUE TITLE
Automatically updating ruby-build

### ISSUE THREAD

**Issue by eregon** [asdf-vm/asdf-ruby#217]
It seems a frequent issue (notably #207, #204 but I think quite a few others)  is that ruby-build in this plugin can be quite outdated.

For instance the current release is `ruby-build 20210611` but this plugins default to:
https://github.com/asdf-vm/asdf-ruby/blob/f134c2df390bd8b32c33de5330d61e77b70ae739/lib/utils.sh#L1

The README also says:
> By default asdf-ruby uses the latest release of ruby-build, but you can choose your own branch/tag through the ASDF_RUBY_BUILD_VERSION variable:

But this is misleading, asdf-ruby will often not use the latest release.
Unless maybe there is already some mechanism to auto-update ruby-build?

It would also avoid the need for many PRs like https://github.com/asdf-vm/asdf-ruby/pull/208

Some ideas:
* `ruby-build` `master` is fairly stable, it should be fine to just use that. This is what is recommended to update ruby-build in rbenv: https://github.com/rbenv/ruby-build#upgrading. Releases are mostly made IIRC for Homebrew.
* Find out the latest release using the GitHub API, i.e., the API equivalent of https://github.com/rbenv/ruby-build/releases/latest, and then I would think `asdf plugin update ruby` would be enough to get the latest release (it would always download the latest ruby-build release, unless it's already using it).
* Get some notification here or automated PR whenever there is a ruby-build release. Seems significantly more complicated but still a possible way.

Apologies if I missed something, I'm a ruby-build maintainer, and I am currently not using asdf, but would like to help keep the version of ruby-build in asdf-ruby always updated so users can get the latest Rubies/fixes.

**Comment by pboling** [comment]
Option 1, using master, and auto-updating, similar to how homebrew does, would be my preference.

**Comment by Stratus3D** [comment]
> The README also says:
>
>>    By default asdf-ruby uses the latest release of ruby-build, but you can choose your own branch/tag through the ASDF_RUBY_BUILD_VERSION variable:

We should improve the wording in the readme to make it clear we have to manually bump the version here when a new version of ruby-build is released.

> The "slight delay" was weeks or months from what I've seen on this issue tracker, e.g., #217

Whenever someone requests the latest version of ruby-build, it typically takes us less than 24 hours to get asdf-ruby updated. I realize that we don't get timely requests for updates when some versions of ruby-build are released.

> Get some notification here or automated PR whenever there is a ruby-build release. Seems significantly more complicated but still a possible way.

I think this is the route I am going to go. I have subscribed to new releases for ruby-build, so I should always have asdf-ruby updated with the latest version (assuming there are no breaking changes) within 24 hours.

As stated before, I don't think that automatically updating to the latest master/head is wise for any dependency, and ruby-build is a dependency of this project.

**Comment by eregon** [comment]
> As stated before, I don't think that automatically updating to the latest master/head is wise for any dependency, and ruby-build is a dependency of this project.

Maybe `asdf plugin update ruby` or some other command could be used to update to the latest ruby-build (master or latest release)? Given there are fairly frequent `ruby-build` releases I doubt manually updating & making a PR on every release is going to scale good enough.

**Comment by Stratus3D** [comment]
It would be nice if ruby-build was able to automatically retrieve new versions. The asdf-erlang plugin uses kerl, which is able to retrieve a list of all available Erlang versions. And most asdf plugins automatically retrieve new versions as well. I'd rather not **have** to update anything when a new version comes out. I understand that sometimes patches are necessary for certain OS/version combinations and that isn't always possible, but I think it's a nice default behavior.

**Comment by eregon** [comment]
> It would be nice if ruby-build was able to automatically retrieve new versions. 

It basically has, see https://github.com/rbenv/ruby-build#upgrading
So assuming it's cloned via git, it's:
```
$ git -C "$where_ruby_build_is_installed" pull
```
And that's "as an rbenv plugin", i.e., I would think the source of most usages of `ruby-build`.

So I think it would make a lot of sense to have an asdf-ruby command to update ruby-build.

I guess we could think about adding `ruby-build --update` or so, if maybe that feels better?
You would still need to expose it some way to asdf though, so I don't it would change much.

i.e., whether a software pulls some metadata or the whole repository does not make it less stable.
In fact, I even argue the opposite in https://eregon.me/blog/2021/06/04/review-of-ruby-installers-and-switchers.html#ruby-install (just some versions metadata can easily break if some change in addition to metadata needs to be done like new dependencies, new URLs, etc)

**Comment by Stratus3D** [comment]
> i.e., whether a software pulls some metadata or the whole repository does not make it less stable.
In fact, I even argue the opposite in https://eregon.me/blog/2021/06/04/review-of-ruby-installers-and-switchers.html#ruby-install (just some versions metadata can easily break if some change in addition to metadata needs to be done like new dependencies, new URLs, etc)

I agree that it doesn't necessarily make it more stable to only update the version list rather than all the code, but **it does guarantee that the ruby-build API stays the same**. Ultimately dependencies should be locked to specific revision, and ruby-build is a dependency. This is best practice when it comes to dependency management, and isn't unusual. I understand this makes things more difficult for some, but I believe it is the right way to do things.

I am going to close this issue shortly unless someone proposes a solution that we have not considered that still allows us to lock to a specific tag of ruby-build.

**Comment by eregon** [comment]
> it does guarantee that the ruby-build API stays the same

Indeed, but that's the case even when updating ruby-build because the "API" is `ruby-build VERSION PREFIX` and that will most likely never change. i.e., the "API" is so small that breaking is not a risk in practice.

> I am going to close this issue shortly

If what you said above (quoted below) is done, then indeed it's fine to close:

> I think this is the route I am going to go. I have subscribed to new releases for ruby-build, so I should always have asdf-ruby updated with the latest version (assuming there are no breaking changes) within 24 hours.

I suspect it's going to be annoying, but that can probably be solved with some automation, which can be a separate issue.

**Comment by Stratus3D** [comment]
Closing this ticket as I've been manually updated ruby-build versions since last commenting on this issue. I don't think I've ever gone more than 48 hours before getting a version bump merged, so I am happy with this solution for now. Eventually I will set up some automation to bump the version and open so that all I have to do is review the release.
