### ISSUE TITLE
Support installation of "head" rubies ?

### ISSUE THREAD

**Issue by PragTob** [asdf-vm/asdf-ruby#22]
Hey there,

I'm trying to use asdf as my version manager for everything these days and so also asdf-ruby - works good so far. 

A limitation I've come across is that I can't install "head" versions of rubies e.g. `asdf install ruby jruby-head` - e.g. the current master of CRuby or JRuby. Support for that in the future would be great - but I reckon it's not the most common use case :)

Happy holidays! :star2:

**Comment by Stratus3D** [comment]
We now use `ruby-build` for builds, so if `ruby-build` can do it then we can too. Otherwise it's not possible.

I don't see any head versions listed in the version list produced by `ruby-build` but I do see a couple dev versions, `mruby-dev`, `2.6.0-dev`, etc...

**Comment by PragTob** [comment]
Just came back here after googling "asdf ruby install jruby-head/master" - well hi old self I guess :D 

Thanks @Stratus3D I guess I'll close this and ask over at ruby-build :man_shrugging:

**Comment by dorianmariefr** [comment]
You can do `brew install ruby-build` then `ruby-build --definitions` and see `3.2.0-preview1` for instance then do:

```
asdf install ruby 3.2.0-preview1
```

Not HEAD/master but close enough

**Comment by dorianmariefr** [comment]
Also rvm has `rvm install ruby-head`
