### ISSUE TITLE
Permission denied when uninstalling ruby

### ISSUE THREAD

**Issue by espen** [asdf-vm/asdf-ruby#222]
```bash
asdf uninstall ruby 2.7.3
asdf uninstall ruby 3.0.1
rm: /Users/espen/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/doc/mini_mime-1.1.0/ri/cache.ri: Permission denied
```

The `mini_mime-1.1.0` directory is owned by root. i'm new to asdf but is this normal?

**Comment by Stratus3D** [comment]
No that isn't normal. Did you install `mini_mime`?

**Comment by espen** [comment]
@Stratus3D yes. Either through a Gemfile or I see that this gem is a dependency for the `mail` gem so it could have been installed as part of my default gems. Perhaps that could be the cause of this. And btw the default gem install didn't work my newest install (3.0.2). I did `gem install mail` now and it created `mini_mime` as my user, not root.

**Comment by Stratus3D** [comment]
> And btw the default gem install didn't work my newest install (3.0.2). 

Can you share the output of that installation?

**Comment by Stratus3D** [comment]
Closing due to lack a response with sufficient details to debug this issue.
