### ISSUE TITLE
Different versions Rails

### ISSUE THREAD

**Issue by yenelrb** [asdf-vm/asdf-ruby#23]
Hi man
It's cool, i can use different version ruby, but...
But how i can use different version rails ? Or other gem files ?
So, every time change the Ruby version - reinstall each gem library ?
Really ?

**Comment by Stratus3D** [comment]
@yenelrb yeah, unfortunately you have to reinstall your gems every time you change a project's Ruby version. I believe this is the case with all the Ruby version managers, so it's recommended to use Bundler manage your projects dependencies.

If you have any other questions about asdf-ruby please re-open this ticket.
