### ISSUE TITLE
BUILD FAILED (macOS 12.0.1 using ruby-build 20211019)

### ISSUE THREAD

**Issue by andersennl** [asdf-vm/asdf-ruby#232]
Hi, I'm trying to install Ruby 2.6.5. During the installation I see an error which I'll post below. I'm not sure what could cause the error and if this is the right place to address the issue. In case it's relevant I'm using macOS 12.0.1 on an Apple "M1 Pro" MacBook. Please let me know in case you need more information (for instance the full log). Thank you!
```
asdf install ruby 2.6.5
Downloading openssl-1.1.1l.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/0b7a3e5e59c34827fe0c3a74b7ec8baef302b98fa80088d7f9153aa16fa76bd1
Installing openssl-1.1.1l...
Installed openssl-1.1.1l to /Users/niko/.asdf/installs/ruby/2.6.5

Downloading ruby-2.6.5.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.5.tar.bz2
Installing ruby-2.6.5...
ruby-build: using readline from homebrew

BUILD FAILED (macOS 12.0.1 using ruby-build 20211019)

Inspect or clean up the working tree at /var/folders/_r/73hpqvps01n344k0bld57x800000gn/T/ruby-build.20211028131523.17883.QC3g3a
Results logged to /var/folders/_r/73hpqvps01n344k0bld57x800000gn/T/ruby-build.20211028131523.17883.log

Last 10 log lines:
        imemo_type_ids[9] = rb_intern("imemo_parser_strterm");
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../.././include/ruby/ruby.h:1826:56: note: expanded from macro 'rb_intern'
        __extension__ (RUBY_CONST_ID_CACHE((ID), (str))) : \
                                                       ^
1340 warnings generated.
linking shared-object objspace.bundle
422 warnings generated.
linking shared-object date_core.bundle
make: *** [build-ext] Error 2
```

**Comment by RocketSH** [comment]
For any newcomer, I am using MacBook Air (M1, 2020) MacOS Monterey 12.2.1. When I try to install Ruby 2.6.5 I encountered a similar issue(BUILD FAILED (macOS 12.2.1 using ruby-build 20210928).

I gave command: `RUBY_CFLAGS="-w" asdf install ruby 2.6.5` a try, it also worked for me.

**Comment by devAffe** [comment]
I'm using a M1 Mac as well with macOS 13.0.1 and I tried this command with the ruby version 3.2.2 but it didn't work for me. I still got the message that the build had failed. 
BUILD FAILED (macOS 13.0.1 using ruby-build 20230717)

**Comment by RocketSH** [comment]
Hey @devAffe Just guessing, did you install a c library before? It's worth checking your global environment variables again, if there are `CFLAGS` defined it might cause this error, in this case we can consider using `direnv` to manage environment variables by directory.
