### ISSUE TITLE
Can't install any version (without using a workaround)

### ISSUE THREAD

**Issue by jaydorsey** [asdf-vm/asdf-ruby#239]
Hello, I wanted to report something that I thought seemed unexpected.

- I've pulled down the latest versions of asdf-vm/asdf-ruby (tried with both master branch and latest release branch)
- I'm using a new/clean terminal window
- macOS m1, zsh
- I tried this with both 3.0.3 and 2.75

![image](https://user-images.githubusercontent.com/191564/143480937-b69f06e0-5343-4a4c-a4f1-4345ca753d19.png)

I found my ruby-build version locally and it seems correct/current/expected:

![image](https://user-images.githubusercontent.com/191564/143481128-e2d4cc74-ce55-41b7-bb7e-5f63c248fb63.png)

I did a _little_ bit of debugging on [these lines](https://github.com/asdf-vm/asdf-ruby/blob/c684fadea52284583802dfaf7705c92a78a085b5/bin/install#L35-L37)

`$matching_version` actually returns `3.0.3` correctly, but it fails inside of that if block.

I resolved it by deleting the if block (because I knew the version was correct). I'm not sure what the correct fix should be or the root cause and I wasn't able to trace with the `-n` flag in that statement was doing but I'm wondering if it's not related to either zsh or my bash version.

`/usr/bin/env bash` returns the following (this looks like my homebrew bash):

```
GNU bash, version 5.1.8(1)-release (aarch64-apple-darwin20.4.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

A few other things might be relevant:

- I also upgraded homebrew bash to 5.1.12 and have the same issue
- I tried with an older version of ruby, 2.7.4

I tried the `-n` snippet in zsh and bash and both always seem to exit early:

![image](https://user-images.githubusercontent.com/191564/143482176-fe0f461b-78ac-4a24-8df2-d2dfa15d3b6d.png)

![image](https://user-images.githubusercontent.com/191564/143482261-4c0079a5-c072-4a41-aae7-66ecfc1a53da.png)

I'm not an expert in bash, but I the docs [here](https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_01.html) say that `-n` is "true if the string is non-zero" so I think this might be a bug.

I'm happy to do a small pull request on this, but I didn't see anyone else report an issue so I'm not sure if this is a bug or if it's me (I have some custom zsh/shell stuff setup). Was hoping someone can confirm this behavior.

Update: Just noticed this other behavior as well

```
asdf install ruby 2.7.4 # returns "Version not found", but it definitely is
asdf install ruby 3.0.5 # silent exit
```

**Comment by davidcelis** [comment]
I can confirm this is happening to me too. I'm on macOS and use `fish`; `Version not found` is being returned when I try to install any existing version of Ruby, whether its one of the new ones or a version thats been around for ages and was previously installable.

**Comment by il-santo** [comment]
Same problem here. 

The test is actually wrong. It should be:

```
  if [[ -z "$matching_version" ]]; then
    errorexit "Version not found"
  fi
```

**Comment by seuros** [comment]
@il-santo can you open a PR?

**Comment by il-santo** [comment]
Uh, I didn't even fork the repo... BTW, if you need a PR, I'll do It.

**Comment by il-santo** [comment]
> @il-santo can you open a PR?

Done.

**Comment by tamvm** [comment]
please merge

**Comment by luisdelarosa** [comment]
I see the same behavior when trying to install ruby 2.7.2 using asdf 0.8.1 installed via homebrew on Ubuntu 20.04.3 on WSL2 on Windows 10.

**Comment by jaydorsey** [comment]
There's an open PR at #240 that will fix the immediate issue. I have a branch [here](https://github.com/jaydorsey/asdf-ruby/commit/c6db9a376d1b01af9a5028f11fdfb96ab8902d60) showing one small additional change that we can make. I'm waiting to see if the original gets merged in as-is or not.

It's a holiday weekend (here in US at least) so the PR may not get merged immediately. If this is blocking anyone immediately they can just make the modifications directly to `~/.asdf/plugins/ruby/bin/install` as a workaround

**Comment by panSarin** [comment]
I still have the same issue, even after #240 patch;/

**Comment by ritajie** [comment]
Maybe `asdf plugin update ruby` can help you.

```bash
$ asdf install ruby 2.7.7
Version not found

$ asdf plugin update ruby

$ asdf install ruby 2.7.7
Success!
```

/cc @panSarin
