### ISSUE TITLE
Migrating from chruby isn't that simple

### ISSUE THREAD

**Issue by maxim** [asdf-vm/asdf-ruby#24]
2 problems I've encountered so far with migration from chruby.

1. The naming convention for rubies was different, as in the directory `ruby-2.3.2` should become `2.3.2` (I renamed manually).

2. More importantly, the shebang in the bin files of chruby is hardcoded to the old location

```
$ head -n1 ~/.asdf/installs/ruby/2.3.2/bin/gem
#!/Users/max/.rubies/ruby-2.3.2/bin/ruby
```

I will probably just reinstall ruby instead of fixing this by hand.

**Comment by Stratus3D** [comment]
@maxim that's true, it looks like Rubies installed by asdf-ruby also have hardcoded shebangs. I suppose it would be possible to write a simple shell script to replace the shebang lines, but I'm not sure it's worth it.

**Comment by rmoriz** [comment]
The key seems to be compilig ruby with `--enable-load-relative`.

We're using ruby-build to pre-build ruby installs for various users/servers.


```
…
export RUBY_VERSION=2.3.3
export RUBY_CONFIGURE_OPTS="--disable-install-doc --enable-load-relative"
ruby-build --verbose $RUBY_VERSION ~/.asdf/installs/ruby/$RUBY_VERSION
asdf local ruby $RUBY_VERSION && asdf list ruby && asdf reshim ruby ${RUBY_VERSION}
…
```

While this won't fix existing installs, it might be worth adding to asdf-ruby's `install` script.

**Comment by Stratus3D** [comment]
I've removed this migrating rubies section from the readme since it's simpler for users to reinstall than it is to migrate. @rmoriz if you think `--enable-load-relative` is worth having can you open another issue for it? Thanks!

**Comment by rmoriz** [comment]
As far as I understand, rvm uses `--enable-load-relative`. That said, `asdf-ruby`'s README shows the path to https://github.com/rbenv/ruby-build#custom-build-configuration so if someone cares, they should find this issue and the solutions or the hint to the solution somewhere else. 

I understand this is an edge case.
