### ISSUE TITLE
rails -v shim shows v7 even though v7 is not installed

### ISSUE THREAD

**Issue by sshaw** [asdf-vm/asdf-ruby#246]
Rails 7 _was_ installed but I have since removed it. Now: 
```
~/code/ruby >which rails
/Users/sshaw/.asdf/shims/rails
~/code/ruby >which gem
/Users/sshaw/.asdf/shims/gem
~/code/ruby >rails -v
Rails 7.0.0
~/code/ruby >gem list '^rails$'

*** LOCAL GEMS ***

rails (6.1.4.4)
```
Running `rails new` adds v7 to the `Gemfile`. Running `rails _6.1.4.4_ new` works as expected.

**Comment by Stratus3D** [comment]
@sshaw I doubt asdf itself would have caused this issue. Did you ever figure out what caused this? We never got any other reports of asdf causing this issue with rails.

**Comment by Stratus3D** [comment]
Closing since I don't believe this is an issue with asdf-ruby.

**Comment by sshaw** [comment]
> Did you ever figure out what caused this? We never got any other reports of asdf causing this issue with rails.

Cannot recall but I suppose I installed Rails 7, uninstalled it, but `/Users/sshaw/.asdf/shims/rails` somehow still resolved 7. 
Alternatively, `rails` at the v7 location could have been remembered by the shell (e.g., `hash` is Bash) whilst `which` found earliest location in `PATH` 🤷‍♂️
