### ISSUE TITLE
Change the way ruby-build is used (jruby-9.3.3.0 can't be installed)

### ISSUE THREAD

**Issue by hurricup** [asdf-vm/asdf-ruby#249]
Kind of continuation of discussion from https://github.com/asdf-vm/asdf-ruby/issues/120#issuecomment-502461172

It's really annoying that we cant install just released things already supported in master of ruby-build. Because it's version hardcoded to the asdf-ruby.

Please, change it by default to the `HEAD` or provide runtime possibility to enforce particular ruby-build commit, like `WITH_RUBY_BUILD=some_hash asdf install ruby ....`.

**Comment by chadlwilson** [comment]
I believe you can already do this? I managed to get `9.3.3.0` down with `ASDF_RUBY_BUILD_VERSION=HEAD asdf install ruby jruby-9.3.3.0`

https://github.com/asdf-vm/asdf-ruby/blob/d0e5a20c1887f9cd18658e62b731f29c356c0a53/lib/utils.sh#L1

**Comment by hurricup** [comment]
Oh god, I missed that. Thank you!

**Comment by chadlwilson** [comment]
Thanks for raising from my perspective anyway, I came hunting for this because I was stuck with the same issue and wondering how to install "fresh" stuff. Your query motivated me to dig in the source 👍
