### ISSUE TITLE
gemset like support? [question]

### ISSUE THREAD

**Issue by jasdeepsingh** [asdf-vm/asdf-ruby#25]
Just started looking into `asdf` and as a result `asdf-ruby` and I was wondering if there's a way to isolate the gem versions under the same ruby version somehow? Very much like the concept of gemsets in `rvm`?

Example: 

- Project A 
  - `ruby-2.3.1`
  - `rails 5.0.1`

-  Project B 
   - `ruby-2.3.1`
   - `rails 4.2.5`

**Comment by HashNuke** [comment]
@jasdeepsingh No gemset support planned. I guess this might be a bit muddy to implement. Would love suggestions/contributions on implementation.

**Comment by jasdeepsingh** [comment]
@HashNuke thanks, I'll familiarize myself with the parent `asdf` project and the plugin ecosystem to see how this could be achieved. We can close this issue for now.
