### ISSUE TITLE
Unable to install ruby 2.3.6 on M1 MacBook Pro Monterey

### ISSUE THREAD

**Issue by reddysatwik** [asdf-vm/asdf-ruby#251]
I have been trying to install ruby 2.3.6 but I am seeing the following error.

```
asdf install ruby 2.3.6 
Downloading openssl-1.0.2u.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/ecd0c6ffb493dd06707d38b14bb4d8c2288bb7033735606569d8f90f89669d16
Installing openssl-1.0.2u...

BUILD FAILED (macOS 12.1 using ruby-build 20220125)

Inspect or clean up the working tree at /var/folders/9t/d0t6vsrs2hl1rj6_gfflys2m0000gq/T/ruby-build.20220210162122.16339.KRlazS
Results logged to /var/folders/9t/d0t6vsrs2hl1rj6_gfflys2m0000gq/T/ruby-build.20220210162122.16339.log

Last 10 log lines:
      _dgram_write in libcrypto.a(bss_dgram.o)
      _RAND_query_egd_bytes in libcrypto.a(rand_egd.o)
      ...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [link_a.darwin] Error 1
make[3]: *** [do_darwin-shared] Error 2
make[2]: *** [libcrypto.1.0.0.dylib] Error 2
make[1]: *** [shared] Error 2
make: *** [build_crypto] Error 1
```

Any ideas on a fix?

**Comment by pboling** [comment]
You have a new machine and are attempting to run a ridiculously old Ruby that came out before the M1 architecture existed.

In your build it is clear it is attempting to build for `i386`, when it should be building for `arm64`.

```
ld: symbol(s) not found for architecture i386
```

There will probably never be a fix.  All rubies prior to 2.7 are not safe to run (Note the OpenSSL it is trying to use: `openssl-1.0.2u`, and then read about the non-trivial work you would have to do to run that securely - https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/).

Upgrade ASAP!

**Comment by JCTD** [comment]
@pboling Thanks, while I agree with you that Ruby 2.3.6 is old. Our team is not ready to upgrade yet. However, the reason asdf is unable to install Ruby 2.3.6 on an M1 is due to incorrect install script rather than the fact that Ruby 2.3.6 is old. I was able to install Ruby 2.3.6 with asdf just a month ago so something changed on asdf recently that caused this.

**Comment by pboling** [comment]
`asdf` uses `ruby-build` under the hood.  It will update `ruby-build` to the latest `HEAD` version from time to time (when you ask it to install rubies especially!). All you need to do it revert to the `ruby-build` checkout that `asdf` is using (it is buried some where on your hard drive!) to the version that was working... and then make sure it doesn't update it again, ever.  You could report the bug to `ruby-build` too.

In any case, it is not a bug in `asdf-ruby`.
