### ISSUE TITLE
Request: Support for precompiled Ruby binaries

### ISSUE THREAD

**Issue by jwarner112** [asdf-vm/asdf-ruby#275]
Note: I've written this with the goal of tasking myself with implementing it myself, and just want to gather early opinions and feedback before committing the time.

I've been looking at [Fullstaq Ruby](https://fullstaqruby.org/) and noticed [#76](https://github.com/fullstaq-ruby/server-edition/discussions/76) where it asks about ASDF supporting their project. Because this Ruby plugin is coupled so heavily to `ruby-build`, the creator of Fullstaq doesn't anticipate being able to do this integration _without_ modifying the plugin, first.

All that needs to happen is for the plugin to be able to recognize when a precompiled binary needs fetched. It could be through pattern-matching the string, or through something more sophisticated, perhaps inspired by the [Golang plugin](https://github.com/kennyp/asdf-golang). Thoughts?

**Comment by Stratus3D** [comment]
I think this is already being discussed on https://github.com/asdf-vm/asdf-ruby/issues/57, lets continue the discussion there.
