### ISSUE TITLE
IntelliJ won't detect Ruby interpreter installed using asdf-vm whatsoever 

### ISSUE THREAD

**Issue by hawkeyes21** [asdf-vm/asdf-ruby#276]
***IDE and OS version***

IDE - IntelliJ IDEA 2022.1.1 (Ultimate Edition): Build #IU-221.5591.52, built on May 11, 2022
OS - Pop!_OS 22.04 LTS

***What steps will reproduce the issue?***

Install the latest version of Ruby using asdf-vm
Create a new Ruby project in IntelliJ

***What is the expected result?***
Intellij should detect the Ruby interpreter installed using asdf-vm

***What happens instead?***
IntelliJ detects Ruby interpreter from the location `/usr/bin/ruby` instead. No Ruby interpreter was installed at this location. Upon manually navigating to that directory, no Ruby interpreter is found. Also unable to delete this file using IntelliJ.
When trying to manually change the interpreter to asdf-vm location (`/home/jaymin/.asdf/shims/ruby`), it throws the following error:
> Error configuring SDK: Unable to read RbConfig for ruby (/home/jaymin/.asdf/shims/ruby). Please make sure that /home/jaymin/.asdf/shims/ruby is a valid home path for this SDK type.

***Log file***
The log file is attached herewith 
[idea.log](https://github.com/asdf-vm/asdf-ruby/files/8858588/idea.log)

**Comment by pboling** [comment]
`/home/jaymin/.asdf/shims/ruby` is not a valid home path for a ruby installation, it is just a shim.

Are you using a JRuby install with IntelliJ?

If not, why not?  Were you expecting to use MRI Ruby with IntelliJ?

Why are you not using the equivalent Ruby IDE, called RubyMine, from the same company?

This is almost certainly an issue for IntelliJ, not asdf-ruby, as IntelliJ would have to add support for asdf-ruby, not the other way around.  In fact they did add support in 2018, but maybe you have found a bug.

Please read this thread:
https://youtrack.jetbrains.com/issue/RUBY-20370

You'll need to register for an account and submit your issue there ^ as well.

**Comment by hurricup** [comment]
This is really looks like a question to rubymine tracker. But anyway, if RM or ruby plugin unable to detect asdf by itself (usually this happens if it's installed in unusual place), you should add it manually, but specify path to `asdf` binary, not ruby. However, it's really strange, seems you have a pretty default path. 
Please, fill an issue in https://youtrack.jetbrains.com/issues/RUBY

**Comment by hawkeyes21** [comment]
> `/home/jaymin/.asdf/shims/ruby` is not a valid home path for a ruby installation, it is just a shim.
> 
> This is almost certainly an issue for IntelliJ, not asdf-ruby, as IntelliJ would have to add support for asdf-ruby, not the other way around. In fact they did add support in 2018, but maybe you have found a bug.
> 
> Please read this thread: https://youtrack.jetbrains.com/issue/RUBY-20370
> 
> You'll need to register for an account and submit your issue there ^ as well.
> 
> Out of curiosity, since I have never used IntelliJ, only RubyMine:
> 
>     1. Are you using a JRuby install with IntelliJ?
> 
>     2. If not, why not?  Were you expecting to use MRI Ruby with IntelliJ?
> 
>     3. Why are you not using the equivalent Ruby IDE, called RubyMine, from the same company?

1. No, I'm not using JRuby. I mean, I've only installed Ruby using asdf-vm. Not even sure why the Ruby file exists in /usr/bin directory
2. I'm not really sure about this one. Do I have to install an additional utility to work with IntelliJ/RubyMine, because the current setup works fine with VSCode
3. I tried with RubyMine, but I'm facing the same issue.

I posted this issue on YouTrack - https://youtrack.jetbrains.com/issue/RUBY-29810/IntelliJ-wont-detect-Ruby-interpreter-installed-using-asdf-vm-whatsoever

**Comment by hawkeyes21** [comment]
> This is really looks like a question to rubymine tracker. But anyway, if RM or ruby plugin unable to detect asdf by itself (usually this happens if it's installed in unusual place), you should add it manually, but specify path to `asdf` binary, not ruby. However, it's really strange, seems you have a pretty default path. Please, fill an issue in https://youtrack.jetbrains.com/issues/RUBY

I tried using the directory mentioned in the question as well as `/home/jaymin/.asdf/installs/ruby/3.1.2/bin/ruby` directory, but I get the same error. Is there any other directory I should be trying?

**Comment by hurricup** [comment]
Oh. now I remember. As I mentioned in the issue, the problem is
```
/home/.../.asdf/installs/ruby/3.1.2/bin/ruby: /usr/lib/x86_64-linux-gnu/libcrypt.so.1: version `XCRYPT_2.0' not found (required by /home/.../.asdf/installs/ruby/3.1.2/lib/libruby.so.3.1)
/home/.../.asdf/installs/ruby/3.1.2/bin/ruby: /usr/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/.../.asdf/installs/ruby/3.1.2/lib/libruby.so.3.1)
/home/.../.asdf/installs/ruby/3.1.2/bin/ruby: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/.../.asdf/installs/ruby/3.1.2/lib/libruby.so.3.1)
```
And this looks like something specific to your system set up.

**Comment by pboling** [comment]
Seems like you need to install XCode command line tools?  Are you able to run a basic ruby command on the command line?

**Comment by hurricup** [comment]
Yes, there is something tricky with system. Causing errors above

**Comment by hawkeyes21** [comment]
> Yes, there is something tricky with system. Causing errors above

FYI earlier there was also some issue with the newer version of OpenSSL, which was not allowing to install multiple Ruby packages. It was resolved by downgrading it to version 1.1

**Comment by hawkeyes21** [comment]
Update:
I installed RubyMine and Intellij using JetBrains Toolbox and it seems to fix the issue. Earlier, both these IDEs were installed using Pop!_Shop.
Ruby versions are being detected automatically.

**Comment by vlazar** [comment]
I followed [How to: Debug detecting of Ruby interpreters﻿](https://www.jetbrains.com/help/ruby/ruby-version-managers.html#how_debug_detection) and added `#org.jetbrains.plugins.ruby.version.management.asdf.AsdfSdkRefresher` in Custom Debug Log Configuration dialog.

Checking logs revealed this error:

```
zsh: no such file or directory: /usr/local/Cellar/asdf/0.11.0/asdf.sh
```

Which is correct. The correct path, at least in asdf 0.11.0 is
```
/usr/local/Cellar/asdf/0.11.0/libexec/asdf.sh
```

Creating the link and restarting IDE fixed the issue for me
```
ln -s /usr/local/Cellar/asdf/0.11.0/libexec/asdf.sh /usr/local/Cellar/asdf/0.11.0/asdf.sh
```

**Comment by yihou** [comment]
@vlazar symbolic link `asdf.sh` method does not work for `asdf` version 0.11.1 🥲

**Comment by pboling** [comment]
There was a reshim bug in asdf, not sure of current status, but I had similar problems with the switch from 0.10.0 to 0.10.1, and I ended up reinstalling asdf.

**Comment by pdm-jd** [comment]
For future readers, `asdf reshim` fixed it in `v0.13.1-0586b37`

**Comment by jacegu** [comment]
For future reference, I experienced the same issue today with asdf 0.15.0:

- I followed the debugging steps suggested by Jetbrains [here](https://www.jetbrains.com/help/ruby/ruby-version-managers.html#how_debug_detection).
- In the logs, I could clearly see errors on the line of this one for all asdf-installed ruby versions:
    ```
    2025-01-02 13:14:56,759 [  14961]   WARN - #c.i.o.p.i.SdkConfigurationUtil - Error creating or configuring sdk: homeDir=[file:///Users/jacegu/.asdf/installs/ruby/3.2.4/bin/ruby]; sdkType=[RUBY_SDK]; additionalData=[RubySdkAdditionalData{myInitializedPaths=true, myTemporaryRoots=null, myGemsBinDirectory='null', myGemsRootsUrls=null, myLanguageLevel=null, myPlatform='null', myVersionManagerSdkAdditionalData=org.jetbrains.plugins.ruby.version.management.asdf.AsdfSdkData@14201f8, myRbConfig=org.jetbrains.plugins.ruby.ruby.sdk.RbConfig@56b78376, myNormalizedVersionString='null', myIsWritable=false}]; customSdkSuggestedName=[asdf: 3.2.4]; sdk=[null]
    java.lang.RuntimeException: Could not get RubyGems environment for asdf: 3.2.4 Version:null Path:(/Users/jacegu/.asdf/installs/ruby/3.2.4/bin/ruby)
    ```
- I could also identify an error similar to the one described [here](https://github.com/asdf-vm/asdf-ruby/issues/276#issuecomment-1363987245):
    ```
    2025-01-02 13:14:56,759 [  14961]   WARN - #o.j.p.r.g.g.GemRunner - Error getting raw environment for asdf: 3.2.4 Version:null Path:(/Users/jacegu/.asdf/installs/ruby/3.2.4/bin/ruby): bash: line 1: /opt/homebrew/Cellar/asdf/0.15.0/asdf.sh: No such file or directory
    ```
- Running `asdf reshim` did not help with this issue for some reason.
- I recreated the symlink:
    ```
    ln -s /opt/homebrew/Cellar/asdf/0.15.0/libexec/asdf.sh /opt/homebrew/Cellar/asdf/0.15.0/asdf.sh
    ```
- It solved the problem for me.

**Comment by brentredd** [comment]
If you're having problems with RubyMine since updating asdf to v0.16+: https://youtrack.jetbrains.com/issue/RUBY-33864/Support-asdf-0.16
