### ISSUE TITLE
Ruby build cant donwload ruby version

### ISSUE THREAD

**Issue by JoaoPedroAssis** [asdf-vm/asdf-ruby#278]
After executing `asdf install ruby 2.7.2`, I received the following error message:

```bash
$ asdf install ruby 2.7.2  
Downloading ruby-2.7.2.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.2.tar.bz2
error: failed to download ruby-2.7.2.tar.bz2

BUILD FAILED (Ubuntu 20.04 using ruby-build 20220610)

```

This seemed to be a network problem, but asdf worked fine in yarn. I've already installed all system libraries and requirements, what is wrong with my installation? I'm using Ubuntu 20.04

**Comment by Stratus3D** [comment]
`$ curl -v https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.2.tar.bz2` yields a 200 status code response and indicates there is a file that can be downloaded. I'm guessing this was either a network issue or a temporary issue on the `cache.ruby-lang.org` server.
