### ISSUE TITLE
I can't install python on ubuntu 22.04 using asdf-vm

### ISSUE THREAD

**Issue by Alessandro-Neves** [asdf-vm/asdf-ruby#280]
i'm try to install python latest version using asdf-vm. nodejs and java is installed sucessfully.

alessandro@Aspire-515:~$ asdf install python latest
python-build 3.10.5 /home/alessandro/.asdf/installs/python/3.10.5
Downloading Python-3.10.5.tar.xz...
-> https://www.python.org/ftp/python/3.10.5/Python-3.10.5.tar.xz
Installing Python-3.10.5...

BUILD FAILED (Ubuntu 22.04 using python-build 2.3.2-1-g207f33fc)

Inspect or clean up the working tree at /tmp/python-build.20220702234929.92416
Results logged to /tmp/python-build.20220702234929.92416.log

Last 10 log lines:
  File "/tmp/python-build.20220702234929.92416/Python-3.10.5/Lib/ensurepip/__init__.py", line 277, in _main
    return _bootstrap(
  File "/tmp/python-build.20220702234929.92416/Python-3.10.5/Lib/ensurepip/__init__.py", line 193, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
  File "/tmp/python-build.20220702234929.92416/Python-3.10.5/Lib/ensurepip/__init__.py", line 93, in _run_pip
    return subprocess.run([sys.executable, '-W', 'ignore::DeprecationWarning',
  File "/tmp/python-build.20220702234929.92416/Python-3.10.5/Lib/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/python-build.20220702234929.92416/Python-3.10.5/python', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmpcxc8wujt/setuptools-58.1.0-py3-none-any.whl\', \'/tmp/tmpcxc8wujt/pip-22.0.4-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmpcxc8wujt\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make: *** [Makefile:1280: install] Error 1
alessandro@Aspire-515:~$ asdf info
OS:
Linux Aspire-515 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.10.0-77fd510

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/alessandro/.asdf

ASDF INSTALLED PLUGINS:
java                         https://github.com/halcyon/asdf-java.git master 93242f4
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 05f99c3
python                       https://github.com/danhper/asdf-python.git master 57ef777

**Comment by Stratus3D** [comment]
This is the asdf-ruby project. For asdf-python issues please refer to the asdf-python project - https://github.com/danhper/asdf-python
