### ISSUE TITLE
No Ruby 3.1.2 Available

### ISSUE THREAD

**Issue by jakemumu** [asdf-vm/asdf-ruby#281]
I need to update to ruby 3.1.2 -- is there a way to make it available through asdf?

**Comment by Stratus3D** [comment]
It's available for me:

```
$ asdf list-all ruby | grep -A 2 -B 2 "3.1.2"
3.1.0
3.1.1
3.1.2
3.2.0-dev
3.2.0-preview1
--
rbx-3.100
rbx-3.101
rbx-3.102
rbx-3.103
rbx-3.104
```

Perhaps you need to update to the latest version of asdf-ruby? `asdf plugin-update ruby`.
