### ISSUE TITLE
Ruby 1.9.3-p194 won't install

### ISSUE THREAD

**Issue by RyanMacG** [asdf-vm/asdf-ruby#29]
Running asdf install for 1.9.3-p194 is consistently throwing the error below
```
asdf install ruby 1.9.3-p194
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168  100   168    0     0    226      0 --:--:-- --:--:-- --:--:--   226

gzip: stdin: not in gzip format
```

**Comment by Stratus3D** [comment]
@RyanMacG not all Ruby versions are currently support by `asdf-ruby`. My guess is the place `asdf-ruby` when to download 1.9.3-p194 from didn't even exist, so you probably just downloaded a 404 page or something.

**Comment by Stratus3D** [comment]
I think we really need to just print a nice error here saying that version of Ruby couldn't be downloaded so it's clear to the user that this is the expected behavior when a version isn't available. 

And of course, we'll need to figure out how to add these two versions to asdf-ruby.

**Comment by henrik** [comment]
For others who find this page via Google:

Run `asdf list-all ruby | grep 1.9.3` to see what is available. For me, that's

> 1.9.3-p0
1.9.3-p105
1.9.3-p125
1.9.3-p194
1.9.3-p286
1.9.3-p327
1.9.3-p362
1.9.3-p374
1.9.3-p385
1.9.3-p392
1.9.3-p426
1.9.3-p429
1.9.3-p448
1.9.3-p484
1.9.3-p545
1.9.3-p547
1.9.3-p550
1.9.3-p551
1.9.3-preview1
1.9.3-rc1

Then install the one you prefer. I went with

    asdf install ruby 1.9.3-p551

**Comment by RyanMacG** [comment]
The actual problem seems to be that https://cache.ruby-lang.org/pub/ruby/ list every version of ruby apart from those under 1.9.3 which only has p551 available in the root, the rest are under the 1.9 dir. Wondering what the best approach is here, catch all 1.9.3 requests that aren't for p551 and pull from the alternate path?

**Comment by RyanMacG** [comment]
PR in :smile:

**Comment by Stratus3D** [comment]
This should no longer be an issue now that we are using ruby-build for this.
