### ISSUE TITLE
Ruby 2.7 on M1 mac

### ISSUE THREAD

**Issue by spsaucier** [asdf-vm/asdf-ruby#295]
First off, I have to use `sudo` because `asdf install ruby 2.7.5` begets:
```
Installing ruby-2.7.5...
mkdir: /opt/homebrew: Permission denied
```
I tried updating permissions on `/opt` but get Permission denied on that too.

So I run `sudo asdf install ruby 2.7.5` and get further, failing with this log:
```
...
compiling readline.c
linking shared-object monitor.bundle
linking shared-object pty.bundle
linking shared-object syslog.bundle
compiling objspace_dump.c
readline.c:1904:37: error: use of undeclared identifier 'username_completion_function'; did you mean 'rl_username_completion_function'?
                                    rl_username_completion_function);
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                    rl_username_completion_function
readline.c:79:42: note: expanded from macro 'rl_username_completion_function'
# define rl_username_completion_function username_completion_function
                                         ^
/usr/local/opt/readline/include/readline/readline.h:485:14: note: 'rl_username_completion_function' declared here
extern char *rl_username_completion_function PARAMS((const char *, int));
             ^
1 error generated.
make[2]: *** [readline.o] Error 1
installing default digest libraries
linking shared-object strscan.bundle
make[1]: *** [ext/readline/all] Error 2
make[1]: *** Waiting for unfinished jobs....
installing default nkf libraries
compiling date_parse.c
linking shared-object digest.bundle
compiling console.c
compiling date_strftime.c
installing default console libraries
installing digest libraries
compiling date_strptime.c
installing default date_core libraries
linking shared-object objspace.bundle
linking shared-object io/console.bundle
linking shared-object nkf.bundle
linking shared-object date_core.bundle
make: *** [build-ext] Error 2
```

I was able to install using `arch -x86_64`, but it broke all commands that use ruby, so I don't think that's right.

**Comment by andrewcrook** [comment]
This is probably down to the [ruby-build](https://github.com/rbenv/ruby-build) project  you might want to raise an issue there.  I probably hasn't been update to run on the M1 because people are using ruby v3. Probably needs a new build script and patches. Meantime you could use a VM or Docker for the linux version or port your code to ruby v3.

**Comment by mathieujobin** [comment]
2.7.7 got released with a fix for OS 13 Ventura.

Hope this helps.

**Comment by pboling** [comment]
Ruby 2.7.7 installed via asdf is working on Apple silicon for me, and I'm using it right now.  There is a big difference between homebrew on Apple silicon and homebrew on Intel though.  The error `mkdir: /opt/homebrew: Permission denied` gives me pause.

Of note, Ruby 2.7 is the oldest version of Ruby that will install for me on Apple silicon.

**Comment by andrewcrook** [comment]
mine is  up-to-date as of this minute 

Personally I do not use the` brew asdf` 
I install asdf manually and use its own update feature which is git based.
I have a thing about not using package managers to manage package managers.

`
>asdf info    
OS:
Darwin xxxx-MBP 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64

SHELL:
zsh 5.9 (arm-apple-darwin21.3.0)

ASDF VERSION:
v0.11.3-0adc6c1

ASDF ENVIRONMENT VARIABLES:
ASDF_DIRENV_BIN=/opt/homebrew/bin/direnv
ASDF_DIR=/Users/xxxx/.asdf

ASDF INSTALLED PLUGINS:
direnv                       https://github.com/asdf-community/asdf-direnv.git master 1a140d6
lua                          https://github.com/Stratus3D/asdf-lua.git master 6d4e66a
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 644ada3
php                          https://github.com/asdf-community/asdf-php.git master 1eaf4de
python                       https://github.com/danhper/asdf-python.git master 8505457
ruby                         https://github.com/asdf-vm/asdf-ruby.git master cfc5fb1
`

**Comment by Stratus3D** [comment]
@pboling yes, that is a common issue that should be documented. Anyone is welcome to create a PR for that. Or I will if I get a chance.
