### ISSUE TITLE
[seggggggggggggggggeeg;dsel[=\[p;sdfg/

### ISSUE THREAD

**Issue by ragibkl** [asdf-vm/asdf-ruby#298]

**Comment by ragibkl** [comment]
FML. My kids were playing on my laptop. :man_facepalming: 
I'll close this now.

**Comment by Stratus3D** [comment]
I'm familiar with segfaults but not `seggggggggggggggggeeg` faults. I think your own your own with this one @ragibkl 😆

**Comment by ragibkl** [comment]
Knocks on wood, if my 5 year old decides to become a tech geek like me years from now, I'll show him this as his first GitHub issue!
