### ISSUE TITLE
Improve jruby support and add more jruby versions

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf-ruby#30]
Only one version of jruby is listed by the plugin, and there isn't documentation or integration tests for jruby.

**Comment by Stratus3D** [comment]
@mjcloutier did you try using this plugin to install jruby? There is definitely a lot that needs to be improved, but it may work as is.

**Comment by tuvistavie** [comment]
I am currently using jruby from asdf without any trouble, although I think we should list the available versions.

@mjcloutier Could you give

```
asdf install ruby jruby-9.1.7.0
```

a try please? Thank you!

**Comment by Stratus3D** [comment]
Now that we are using ruby-build this is no longer an issue.

**Comment by grepsedawk** [comment]
Now that ruby-build is in the picture (and I'm sure other asdf improvements), you can type:
`asdf install ruby jruby<Tab>` to get a list of all available jrubies and select your preference.
