### ISSUE TITLE
pre openssl 3.0 compiled rubies

### ISSUE THREAD

**Issue by noraj** [asdf-vm/asdf-ruby#316]
I install some ruby environment back when it was openssl 1.1.1 era.

But now openssl has updated to 3.0. So when I want to install a gem I have this error.

```
$ openssl version                                                                                                                                                                                                    
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)

$ gem install graphql                                                                                                                                                                                                
ERROR:  While executing gem ... (Gem::Exception)                                                                                                                                                                     
    OpenSSL is not available. Install OpenSSL and rebuild Ruby (preferred) or use non-HTTPS sources
```

It means I have to remove all my rubies and reinstall them so they are compiled with openssl 3? The easy workaround is to have openssl 1.1.1 installed in addition of 3.0.

**Comment by SeanSith** [comment]
Can you provide an environment breakdown? What OS, how is ASDF installed, does `which gem` resolve to ASDF's shims directory, where does `which openssl` resolve? By default, ruby-build brings with it a custom compiled OpenSSL appropriate for the Ruby which is being installed, and the `openssl` binary does not get shimmed with ASDF. At the moment, this feels like there may be an environment issue in your setup.

**Comment by noraj** [comment]
Time has passed, I can't reproduce it.
