### ISSUE TITLE
ruby 2.7.7, 3.0.5 and 3.1.3 are out

### ISSUE THREAD

**Issue by mathieujobin** [asdf-vm/asdf-ruby#318]
is it not possible to install without an update to asdf?

download paths are standard, recipe should be the same by default.

**Comment by ashmckenzie** [comment]
https://github.com/rbenv/ruby-build/releases/tag/v20221124 is required which is waiting to be merged at https://github.com/asdf-vm/asdf-ruby/pull/317.

In the meantime, the following works:

```sh
ASDF_RUBY_BUILD_VERSION=v20221124 asdf install ruby 2.7.7
```
