### ISSUE TITLE
Default Gems file final empty line

### ISSUE THREAD

**Issue by jmschp** [asdf-vm/asdf-ruby#335]
# Installing defaults gems skips last gem if no final empty line

Versions:

- MacBook Pro (Retina, 13-inch, Early 2015) (also tested in Apple M1)
- macOS Monterey 12.6.3 (21G419)
- asdf v0.11.1

When installing any ruby version, when it comes to install the default gems, if the file does not have a final empty line, the last gem in the list will not be installed.

**Comment by SeanSith** [comment]
Not speaking for the maintainer, but it's generally considered [bad practice to not finish a text file with a newline in Unix system](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file). Many other utilities fail to process "correctly" when their inputs lack a newline.

**Comment by jmschp** [comment]
@SeanSith 

I agree, but shit happens some time and we might miss a final empty line.

Maybe, this could be just a warning on the docs.

**Comment by Stratus3D** [comment]
Did this ever get fixed? Might be worth making this more flexible and allow a missing newline at the end.

**Comment by jmschp** [comment]
> Did this ever get fixed? Might be worth making this more flexible and allow a missing newline at the end.

@Stratus3D no it wasn't. I just closed the issue.

**Comment by jmschp** [comment]
@Stratus3D 

Can you have a look ate the related PR?

It's a pretty simple change.

**Comment by Stratus3D** [comment]
Fixed with #417 and #424.
