### ISSUE TITLE
Failed to upgrade Ruby version from 3.2.2 to 3.3.0 using asdf

### ISSUE THREAD

**Issue by devcamke** [asdf-vm/asdf-ruby#377]
I am currently using Ruby version 3.2.2 on Ubuntu 22.04, which I installed using asdf. I would like to upgrade to version 3.3.0.

When I run `asdf install ruby 3.3.0`, I keep getting the error message `ruby-build: definition not found: 3.3.0`.

Can anyone guide me on how to upgrade my Ruby version to 3.3.0 using asdf?

**Comment by emmahsax** [comment]
I believe Ruby version 3.3.0 is just not available yet.. not sure if this is due to ruby-build or asdf.

```
$ asdf list all ruby | grep 3.3
1.8.6-p383
1.8.7-p373
2.0.0-p353
2.3.3
3.3.0-dev
3.3.0-preview1
3.3.0-preview2
jruby-9.3.3.0
rbx-3.3
rbx-3.30
rbx-3.31
rbx-3.32
rbx-3.33
rbx-3.34
rbx-3.35
rbx-3.36
rbx-3.37
rbx-3.38
rbx-3.39
```

**Comment by devcamke** [comment]
Updating asdf plugin using the following command  `asdf plugin update ruby` has worked for me. 
You should be able to install 3.3.0 afterwards.
