### ISSUE TITLE
Rubinius support

### ISSUE THREAD

**Issue by AlexWayfer** [asdf-vm/asdf-ruby#38]
Hello!

Are there any plans to support [Rubinius](https://rubinius.com/)?

Thanks.

**Comment by Stratus3D** [comment]
In asdf-ruby directly, no. Rubinius installation appears relatively simple - clone, configure, and build, so it shouldn't be too hard to build manually. We are always open to new asdf plugins, so if you want to write a plugin for Rubinius we'd definitely consider adding it to the asdf readme.

**Comment by AlexWayfer** [comment]
Just... Rubinius is a Ruby language implementation, like JRuby, or even MRI, and they are in `asdf-ruby`... It would be strange to make another plugin for this.

**Comment by AlexWayfer** [comment]
And yes, if the Rubinius installation is simple - it means it's easy to add to `asdf-ruby`, making the life of users even easier.

**Comment by padde** [comment]
How about using https://github.com/rbenv/ruby-build to build rubies? `ruby-build` supports many popular implementations and platforms. It also has a local list of available Rubies which would speed up the `asdf list-all ruby` command significantly (currently fetches list via HTTP on each invocation). There might be a good reason to have a custom toolchain which I don't see - but from an outside perspective it seems like a waste of time. `ruby-build` is doing a great job at this already.

As a side note, you can use `ruby-build` today to install Rubinius for ASDF by simply running

```
ruby-build rbx-3.82 ~/.asdf/installs/ruby/rbx-3.82
```

**Comment by Stratus3D** [comment]
We now use ruby-build. Rubinius is now available.
