### ISSUE TITLE
Add Ruby 3.2.3

### ISSUE THREAD

**Issue by TomNaessens** [asdf-vm/asdf-ruby#381]
https://www.ruby-lang.org/en/news/2024/01/18/ruby-3-2-3-released/

```
SIZE: 20577155
SHA1: 7f553e514cb42751a61c3a560a7e8d727c6931ca
SHA256: af7f1757d9ddb630345988139211f1fd570ff5ba830def1cc7c468ae9b65c9ba
SHA512: 75aecd9cf87f1fa66b24ecda8837a53162071b4f8801dcfd79119a24c6e81df3e3e2ba478e1cc48c60103dfaab12a00cfa2039a621f8651298eba8bd8d576360
```

Changes to ruby-build are in the ruby-build master already, but there's no release as of yet: https://github.com/rbenv/ruby-build/commit/605fb64856373cd3f43f7c855696274fc684e3d5

**Comment by geoffharcourt** [comment]
Changes are now merged to the `master` branch for ruby-build

**Comment by TomNaessens** [comment]
Done through https://github.com/asdf-vm/asdf-ruby/pull/382 🚀
