### ISSUE TITLE
Truffle Ruby Latest?

### ISSUE THREAD

**Issue by ylluminate** [asdf-vm/asdf-ruby#387]
When installing the latest version of MRI Ruby and wanting to keep it up-to-date, we seem to have a simple option to just install "ruby" and keep it up-to-date. Is there a method to easily update other releases such as Truffle Ruby?

**Comment by Stratus3D** [comment]
Yes. For MRI ruby you'd do:

```bash
$ asdf install ruby latest
```

For truffle you can specify a filter/prefix to filter versions by when finding latest:

```bash
$ asdf install ruby latest:truffleruby-
To follow progress, use 'tail -f /var/folders/hp/z_skq1wx0s1f5gvg55gcv_6r0000gp/T/ruby-build.20240321090339.29273.log' or pass --verbose
ruby-build: using openssl from homebrew
Downloading truffleruby-22.3.1-macos-aarch64.tar.gz...
...
```

Hope this helps.
