### ISSUE TITLE
Install ruby 2.3.x on Arch Linux

### ISSUE THREAD

**Issue by franciscoj** [asdf-vm/asdf-ruby#39]
Hi!

I've been trying to use `asdf` to manage my rubies on arch linux for some time and I couldn't because the installation failed no matter what I tried. After some research I managed to get it working by installing `gcc5` and `openssl-1.0` on Arch Linux and then using using:

```
CC=gcc-5 PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig RUBY_EXTRA_CONFIGURE_OPTIONS="--with-openssl-dir=/usr/lib/openssl-1.0" asdf install ruby 2.3.3
```

That solves 2 problems:

1. Ruby 2.3 not being compatible with openssl 1.1 (which is the default one on arch linux)
2. Ruby 2.3 not compiling with gcc 7.1.1 on arch for some other different reason and causing a segfault (as explained here https://bugs.ruby-lang.org/issues/13635#change-65299)

I post it here just in case it can help anybody else, I'd be happy to post it on the wiki if anybody thinks it can be helpful.

Thanks for the amazing work! `asdf` is a super helpful tool!

**Comment by Stratus3D** [comment]
@franciscoj thanks for posting this! I think the wiki would be a good place for guides like this. Feel free to create a page.

**Comment by franciscoj** [comment]
Done! https://github.com/asdf-vm/asdf-ruby/wiki/Ruby-Installation-Problems

And thanks again for the tool!

**Comment by Fs02** [comment]
Hi, I'm having problem installing ruby 2.3.0.

```
configuring openssl
Failed to configure openssl. It will not be installed.
```

It installed, but I cannot use https://rubygems.org as sources

**Comment by Stratus3D** [comment]
@Fs02 perhaps you have openssl installed in a non-standard location? Not sure what the issue is.
