### ISSUE TITLE
Question: can the same version be installed twice with diff name?

### ISSUE THREAD

**Issue by williantenfen** [asdf-vm/asdf-ruby#397]
Can we re-build the same version into another folder and maybe another name? like `ruby-3.1.2-test`

Something like in here: https://github.com/rbenv/rbenv/issues/1171#issuecomment-507685070

**Comment by Stratus3D** [comment]
@williantenfen Not the way you are describing, no. Versions in asdf are uniquely identified by plugin name and version. Typically the plugin name for Ruby would be just `ruby`, and the version would be whatever version you specified to install.

I would not recommend this, but if you did want to install two instances of the same Ruby version you could hack around this by installing the plugin twice. One under the name `ruby` and one under some other name. For example:

```
$ asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
$ asdf plugin add ruby-again https://github.com/asdf-vm/asdf-ruby.git
$ asdf install ruby 3.2.1
$ asdf install ruby-again 3.2.1
```

However, I'd advise against this, and I don't have any intent to add better support for this. A single instance of each version is all you should need per user.

**Comment by williantenfen** [comment]
@Stratus3D Thanks, thats interesting ... 
Just wondering how to build same versions after a kernel upgrade... since usually new members of a project faces issues installing some gem versions which aren't supported on newer kernel versions...

**Comment by Stratus3D** [comment]
Easiest would be to just uninstall and reinstall, but of course you might end up in a scenario where you can't build the version the way it was before.
