### ISSUE TITLE
Make `asdf` work with legacy `.ruby-version` files by default

### ISSUE THREAD

**Issue by preist** [asdf-vm/asdf-ruby#418]
#### Description

I would be very useful if `asdf-ruby` by default, read the `.ruby-version` configuration file instead of requiring additional configuration for this. This would help speed up adoption and make the overall user experience better for those switching from `rvm`. 

A screenshot from the current README file:

<img width="760" alt="image" src="https://github.com/user-attachments/assets/b421716a-2cb8-43cc-ba43-74644a66502a">

**Comment by jmschp** [comment]
Not sure if this issue belongs here. It probably should go in [asdf](https://github.com/asdf-vm/asdf) itself. I think it should behave the same for all plugins.

About the fuzzy matching, you can still make it work in asdf with [asdf-alias](https://github.com/andrewthauer/asdf-alias).

**Comment by Stratus3D** [comment]
Closing as this isn't something we intend on doing **by default**. If you are working in a Ruby project that doesn't have a `.tool-versions` file you'll either need to enable the `legacy_version_file` option or add a `.tool-versions` file to the project.
