### ISSUE TITLE
LoadError when trying to install gems

### ISSUE THREAD

**Issue by inkel** [asdf-vm/asdf-ruby#44]
First of all, thanks for this tool.

I've installed ruby 2.4.1 and after `asdf` finished installing, I tried the following:

```
$ gem install dep
ERROR:  Loading command: install (LoadError)
        cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

Am I missing something else from the installation?

Thanks.

**Comment by seb1441** [comment]
I have the same issue, did you find a fix for this?

**Comment by Stratus3D** [comment]
If anyone else experiences this issue and @seb1441's solution doesn't fix it please reopen this ticket.

**Comment by rjurado01** [comment]
+1 Same error.
