### ISSUE TITLE
default-gems, Bundler and Ruby 2.5.0 install issues

### ISSUE THREAD

**Issue by luislavena** [asdf-vm/asdf-ruby#47]
Hello!

First, thank you for creating and maintaining Ruby plugin for `asdf`! 😄 

With the new Ruby 2.5.0-preview1 release, encountered issues during installation. Found that `bundler` is _bundled_ (no pun intended) on 2.5.0 and because of that, gem installation via `~/.default-gems` hangs.

## Steps to reproduce

Place `bundler` in `.default-gems`
```
$ cat ~/.default-gems
bundler
```

Now, attempt installation of `ruby 2.5.0-preview1`:

```
$ asdf install ruby 2.5.0-preview1
...
```

At the end of installation, notice how output hangs when installing bundler gem. requiring press `Ctrl+C` and resulting on the installation to fail and the new install be removed.

Closer inspection of the issue, seems to be caused by expected user interaction from `gem install`:

```
$ ruby -v
ruby 2.5.0preview1 (2017-10-10 trunk 60153) [x86_64-linux]

$ gem install bundler
bundler's executable "bundle" conflicts with /home/luis/.asdf/installs/ruby/2.5.0-preview1/bin/bundle
Overwrite the executable? [yN]
```

This can be avoided by using `--conservative` modifier:

```
$ gem install bundler --conservative

$ echo $?
0
```

Let me know if a PR for this could be accepted and happily can provide one. 

Thank you again for your plugin!
❤️ ❤️ ❤️

**Comment by nikolay** [comment]
Even version 2.4.2 Ruby cannot install Bundler - possibly for the same reason:

```
Installing bundler gem... FAIL
```

**Comment by Iambchop** [comment]
Just a note that bundler bundling was postponed in the ruby 2.5 release:
https://bugs.ruby-lang.org/issues/12733#note-19
https://github.com/ruby/ruby/commit/7825e8363d4b2ccad8e2d3f5eeba9e26f6656911

**Comment by Stratus3D** [comment]
@luislavena sorry for the late response on this. We recently switched to ruby-build and I just tested this on my machine and I am unable to reproduce. Can you test this again and reopen this issue if the bug still exists? Thanks!
