### ISSUE TITLE
Gemfile version

### ISSUE THREAD

**Issue by chrise86** [asdf-vm/asdf-ruby#53]
Is it possible to use the ruby version specified in the Gemfile? This is a very handy feature with `rbenv` etc

**Comment by Stratus3D** [comment]
Currently no, but nothing prevents us from adding support for that. PRs are welcome!

**Comment by Stratus3D** [comment]
Can you provide a link to the rbenv code that reads the Ruby version out of the Gemfile? It could be useful to anyone who wants to create a PR for this.

**Comment by javierav** [comment]
@Stratus3D https://github.com/aripollak/rbenv-bundler-ruby-version

**Comment by Seanstoppable** [comment]
Tentative fix in #76

**Comment by Stratus3D** [comment]
Fixed by #76
