### ISSUE TITLE
Incorrect subfolder ruby version

### ISSUE THREAD

**Issue by adsteel** [asdf-vm/asdf-ruby#54]
**removed rbenv**
```bash
brew uninstall rbenv
rm -rf ~/.rbenv
# delete rbenv init command from ~/.bashrc
```

**Installed asdf and asdf ruby plugin**
```bash
# followed asdf install steps in readme
$ asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
$ asdf ruby install 2.3.1
$ asdf global ruby 2.3.1
$ which ruby
> /Users/adsteel/.asdf/shims/ruby
$ ruby -v
$ ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]
$ which gem
> /Users/adsteel/.asdf/shims/gem
$ gem -v
> 2.5.1
$ echo $PATH
> /Users/adsteel/.asdf/bin:/Users/adsteel/.asdf/shims:/usr/local/opt/qt@5.5/bin:./node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/adsteel/bin:/usr/local/bin:/usr/local/bin/git/:/usr/local/mysql/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:./bin:/usr/libexec
```
So far so good. Just to be sure...

```bash
$ gem uninstall bundler
$ gem install bundler
```

But things are still incorrect.

```bash
$ irb
irb(main):001:0> Gem.bin_path('bundler', 'bundle')
=> "/Users/adsteel/.asdf/installs/ruby/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/exe/bundle"
irb(main):002:0> 
```

You can see in the install log that the incorrect version is being installed.

```bash
configure: ruby library version = 2.3.0
```

This uses the incorrect version of bundler when I `bundle install`, and so installs the gems incorrectly. It's possible I got myself into this mess with how I uninstalled rbenv, but I'm not really sure what I did wrong if that's the case.

**Comment by adsteel** [comment]
So I managed to force this by first exporting the `RUBY_CONFIGURE_OPTIONS` as:

```bash
$ export RUBY_CONFIGURE_OPTIONS="--with-openssl-dir=/usr/local/opt/openssl --prefix=/Users/adsteel/.asdf/installs/ruby/2.3.1"
```

But I still can't fire up a Rails server. Lots of errors. Comment out the code causing one and another pops up.

**Comment by 0xadada** [comment]
@adsteel did you ever find a fix for this?

**Comment by adsteel** [comment]
@0xadada I did not. I've changed systems since and have not seen it again though. We can close it.

**Comment by 0xadada** [comment]
@adsteel hah, i just setup a new system, and have the same problem.

**Comment by adsteel** [comment]
Oof, sorry to hear that. Guess we should keep it open then.

**Comment by 0xadada** [comment]
I figured it out, basically my `$PATH` was set incorrectly. I set my `$PATH` to:

```bash
export PATH="$HOME/.gem/bin:$PATH"
```
and that fixed it.

**Comment by SeanSith** [comment]
@adsteel @0xadada Can this issue be closed, now?

**Comment by adsteel** [comment]
@SeanSith I've been using asdf for about 8 months now with no issues. Closing seems correct.

**Comment by 0xadada** [comment]
@adsteel @SeanSith nailed it 👍
