### ISSUE TITLE
gem user installation directory is ~/.gem/ruby/<version>

### ISSUE THREAD

**Issue by carolfly86** [asdf-vm/asdf-ruby#55]
I have been using rvm and recently switched to asdf. I found the gem user installation directory is still ~/.gem/ruby/<version>, is it intended? 
I think because of this config, bundle is installed in ~/.gem/ruby/<version>/bin while I would expect it to be installed in ~/.asdf/shims.

**Comment by Stratus3D** [comment]
@carolfly86 that isn't right. `bundle` should be a shim in `~/.asdf/shims`. Can you try upgrading to the latest version of the plugin to see if that fixes the issue? When you run `gem install bundler` take a look at the location for the `gem` executable. If it is not the shim in `~/.asdf/shims` then your installation is not working correctly.

**Comment by Stratus3D** [comment]
Closing this since I am not aware of anything in asdf-ruby that needs to change.
