### ISSUE TITLE
Installation error if curl is unavailable

### ISSUE THREAD

**Issue by dipnlik** [asdf-vm/asdf-ruby#58]
### Steps to reproduce

1. Uninstall `curl`
1. `asdf plugin-add ruby`
1. `asdf install ruby 2.3.1` (will error because `curl` is missing)
1. `asdf install ruby 2.3.1`

### Expected behavior

Should try to install Ruby 2.3.1 since the previous installation failed.

### Actual behavior

Outputs "Ruby is already installed".

### Environment

**OS**: Ubuntu 16.04

**asdf version**: v0.4.1

**Comment by fxn** [comment]
`build-essentials` is also needed, see #59.

**Comment by Stratus3D** [comment]
We now rely on `ruby-build` for builds, so I don't think this should be a problem anymore. Please reopen is this is still an issue.
