### ISSUE TITLE
Can't install gems: `unknown encoding name` error

### ISSUE THREAD

**Issue by justinweiss** [asdf-vm/asdf-ruby#60]
When I install a ruby (specifically, 2.3.5) with `asdf-ruby` using asdf v0.4.3, I get the following error:

```sh
$ gem install bundler
ERROR:  Loading command: install (ArgumentError)
        unknown encoding name: binary
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

This is on Mac OS X 10.13.4. Xcode Command Line Tools and Homebrew are installed, as is libyaml and openssl.

Downgrading asdf to 0.4.1., clearing the build cache in $TMPDIR, and reinstalling Ruby got it working again.

**Comment by Stratus3D** [comment]
Sorry for the late reply. Can you try this with the latest version of asdf (`asdf update`)? It's working for me on OSX 10.14.3 with Ruby 2.3.6.

**Comment by justinweiss** [comment]
No worries! This has been working for me for long enough that I didn't remember that I opened it :-)
