### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by tuxagon** [asdf-vm/asdf-ruby#66]
I was looking into why the current build is failing and it is because the `plugin-test` is pretty opinionated. Essentially what happens is they grab all the versions and then attempt to install the "latest" version which is actually `ree-1.8.7-2012.02` which is, I believe, an obsolete version of ruby anyway. The gcc compiler is having issues on both osx and linux because it is trying to build this much older, specialized version of ruby.

There are multiple directions this could be taken with different trade-offs.

1. Remove obsolete versions of ruby from the list

2. Discuss a different approach upstream with the `plugin-test` that potentially allows for languages like ruby with different kinds of builds to choose what "latest" version to select from the list, rather than just the last in the array.

3. Hack together a more complicated `.travis.yml` file that will account for all the gcc issues despite it not being indicative of a proper ruby version.

4. Sort the list in a different way where the main ruby versions are actually listed at the bottom.

Each option definitely has trade-offs, but something should be done so that the builds can...well.. build again. 😅

**Comment by Stratus3D** [comment]
We opted to go with option 3. See commit eb97e600f43e43479a3835f0f671303c2222d8d3. We eventually want to improve our automated testing for plugins, but in the meantime this should be sufficent. For option 2 we've implemented that in asdf core. See the `--asdf-tool-version` flag here: https://github.com/asdf-vm/asdf/blob/master/docs/creating-plugins.md#testing-plugins
