### ISSUE TITLE
legacy version check doesn't support "ruby-2.5.0" format

### ISSUE THREAD

**Issue by gouthamvel** [asdf-vm/asdf-ruby#69]
I'm working on open source projects and they use .ruby-version file with format a bit different from asdf legacy version.

```
  $ cat .ruby-version
  ruby-2.5.0
```
```
  $ ruby -v
  ruby ruby-2.5.0 not installed
```

it works if I change the content to 2.5.0.

**Comment by Stratus3D** [comment]
We will need to update the asdf-ruby code to parse this version format as well. Thanks for reporting this!

**Comment by kevinjalbert** [comment]
Just wanted to say I ran into the same issue here and stumped me for a little bit. This was for a new Rails 5.2.1 project (so its likely to be a very common issue) as the `.ruby-version` comes pre-baked like this.

**Comment by rmoriz** [comment]
This does not work for me. 

Looks like `get-version-from-legacy-file` is deprecated and  not used by asdf anymore. `list-legacy-filenames` still is just a `cat .ruby-version`
