### ISSUE TITLE
TruffleRuby support

### ISSUE THREAD

**Issue by mdesantis** [asdf-vm/asdf-ruby#71]
All the other main Ruby version management tools now support TruffleRuby: https://github.com/oracle/truffleruby/blob/master/doc/user/ruby-managers.md#installing-truffleruby-with-rvm-ruby-build-or-ruby-install maybe asdf-ruby should keep in pair with them

**Comment by Stratus3D** [comment]
asdf-ruby uses ruby-build underneath. Does the latest version of ruby-build support TruffleRuby? We may just need to update to the latest version of ruby-build.

**Comment by mdesantis** [comment]
yes, I currently forked the project and it seems that updating ruby-build is enough. Would you accept a PR?

**Comment by eregon** [comment]
@mdesantis Thank you for this and the PR, I didn't know about `asdf`.
It's great that it relies on `ruby-build`, that makes it easier to keep it up-to-date.
