### ISSUE TITLE
[Doubt][macOS] asdf global ruby does not set my global version

### ISSUE THREAD

**Issue by crsantos** [asdf-vm/asdf-ruby#81]
Not sure if it's supposed to work like `rbenv`,  but when I type `asdf global ruby 2.4.1`:

* `ruby -v` still shows system ruby 2.3.7 🤔 

I searched some old issues, but found no-one with the same problem.

What am I missing?

## Troubleshooting

* asdf 0.6
* macOS: High Sierra
* asdf installed via homebrew

**Comment by Stratus3D** [comment]
It depends on whether or not you were in a sub directory that had a local ruby version set. If you were in a sub directory with a `.tool-versions` file containing `ruby 2.3.7`, or a `.ruby-version` file containing `2.3.7` that is the expected behavior. If you didn't have local version set and were in your home directory then there is an issue.

**Comment by crsantos** [comment]
I'm on my $HOME `~/` and I only have a `.tool-versions` here with with following content:

```shell
ruby 2.4.1
python 3.7.1
```

I have a folder with a local `.ruby-version` and even a `.tool-versions` set to `2.4.1`, but even using the `legacy_version_file = yes`, I don't have 2.4.1 enabled on that folder.

I just don't know if this is an issue, or some "trash" config that I have left from rbenv, but I'm pretty sure I'm not loading rbenv at all.

Changed to fishshell.com, so my configs are new.

Any other idea?

**Comment by crsantos** [comment]
I'm seeing a pattern here.
Installing via Homebrew I have this problem, **but** git cloning the `0.6.0` branch directly, it works just fine.
So I'm removing the Homebrew installation and using a local git folder instead.

Not sure you want me to debug anything else, but the local git folder is perfectly fine for me, and homebrew installation is not listed on the `README`, so I assume this makes it unofficial 😄

**Comment by Stratus3D** [comment]
I suspect there could possible be a rbenv or system installed Ruby that is on your path before asdf. Maybe the homebrew path comes after the path containing system installed ruby, but when you switc to git installed asdf it comes before system installed ruby? I'm fairly certain this is working correctly, at least for the most widely used cases.

**Comment by Stratus3D** [comment]
Brew has become an "official" way of installing it too, so if you can identify a specific scenario where it breaks please reopen this issue (`type -a ruby` is your friend).

**Comment by crsantos** [comment]
I'll install from brew again **tomorrow** and will come back with more conclusions 👍 
Standby and thank you!

**Comment by crsantos** [comment]
I have some new output when turning on the brew asdf-vm.

**Beware** that I added this to `config.fish`: 
`source /usr/local/Cellar/asdf/*/asdf.fish`

 - to match the `source` command when using the git folder: `source ~/.asdf/asdf.fish`) - is that my problem?

```shell

$ which asdf             
/usr/local/Cellar/asdf/0.6.0/bin/asdf

$ asdf where ruby        
/Users/crsantos/.asdf/installs/ruby/

$ asdf which ruby
/Users/crsantos/.asdf/installs/ruby/2.4.1/bin/ruby

$ asdf global ruby 2.4.1         

$ ruby -v        
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]

$ type -a ruby           
ruby is /usr/bin/ruby
```

**Comment by klappradla** [comment]
Could it be that you also have `ruby` installed via Homebrew _(I think for instance using `vim` from Homebrew will install it)_ and therefore this executable earlier in your `$PATH` @crsantos ?

You could quickly check
```bash
brew list | grep ruby
```

At least for me this also prevented `asdf-ruby` from working rbenv-ish. Aside that, I think using the Homebrew version also has the downside that you'll have to manually move all your plugins when upgrading the package via Homebrew 🤔

**Comment by crsantos** [comment]
Well, I guess I just have `ruby-build`:
```bash
$ brew list | grep ruby                                                                                      
ruby-build
```

But I suppose that's normal, right?
So out of ideas 🤔 

Thanks for the input.

**Comment by hoangtranwork** [comment]
FYI I also have the exact same issue (and the workaround by installing with git instead of brew works).
One thing I notice when installing with brew is that there's no such asdf.sh file (to be put in .zshrc). Maybe that is the catch with installing with brew.

**Comment by jrusso1020** [comment]
@crsantos @hoangtranwork I was having a similar problem to the one described above when installing via homebrew and having `rbenv` previously installed.

I uninstalled rbenv via homebrew and then ran the following commands and it seems to have fixed the problem, I'm now using the proper version of ruby globally. Hopefully this is helpful, obviously it changes slightly depending on your shell

```
echo -e "\n. $(brew --prefix asdf)/asdf.sh" >> ~/.zshrc
echo -e "\n. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash" >> ~/.zshrc
source ~/.zshrc
```

**Comment by smileart** [comment]
For someone how's coming here from Google, consider this scenario I had (macOS):

While installing `asdf install ruby latest` I accidentally quit the terminal where the command was running although on coming back I found `asdf` pretty sure that the latest ruby version was successfully installed, showing it as current and so on, but not actually changing it globally. I tried everything (adding `asdf.sh` higher in my  `~/.zshrc`), `reshim`, etc. – nothing helped. And then I realized that actually Ruby installation has never been finished and `asdf` seems to register the version **before** it's actually compiled and installed. The solution in such case is trivial:

```shell
asdf uninstall ruby 3.1.2  # or whichever version you have
asdf install ruby latest   # and wait till it's indeed installed
asdf global ruby latest    # 
ruby -v                    # should be the latest version, not the system one
```

**Comment by jayqui** [comment]
@jrusso1020's solution almost worked for me, but I noticed that the `asdf` website's [getting started instructions](https://asdf-vm.com/guide/getting-started.html#_3-install-asdf) are slightly different (now, at least) for ZSH and Homebrew:

```shell
echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc
```
