### ISSUE TITLE
`asdf install` doesn't support legacy file

### ISSUE THREAD

**Issue by nicktime** [asdf-vm/asdf-ruby#85]
```
$ asdf plugin-list
elixir
erlang
ruby
$ cat ~/.asdfrc 
legacy_version_file = yes
$ cat .ruby-version 
2.2.2
$ asdf install
Either specify a tool & version in the command
OR add .tool-versions file in this directory
or in a parent directory
$ asdf install ruby 
You must specify a name and a version to install
```

Only explicit one works
```
$ asdf install ruby 2.2.2
Downloading ruby-2.2.2.tar.bz2...
...
```
Expected: `asdf install` alone should be enough to start installation.

**Comment by alecho** [comment]
Do we know if this is a plugin issue or an asdf-vm issue?

**Comment by SeanSith** [comment]
This particular feature is apparently an asdf-vm issue: https://github.com/asdf-vm/asdf/issues/269

However, at this moment, many users (myself included) are having problems with `v0.7.0` not respecting legacy files properly.

**Comment by SeanSith** [comment]
Please try upgrading to the newly release asdf v0.7.1, as legacy file support was fixed in this most recent release. If it works, please consider closing this issue. Thanks!

**Comment by alecho** [comment]
@SeanSith This did fix the issue for me and answers my question that it is indeed a asdf-vm issue.

**Comment by nicktime** [comment]
The problem is still there:
```
$ cat ~/.asdfrc 
legacy_version_file = yes
$ cat .ruby-version 
2.5.4
$ asdf current
elixir         1.5.3    (set by /home/nick/.tool-versions)
erlang         20.1     (set by /home/nick/.tool-versions)
version 2.5.4 is not installed for ruby
ruby           
$ asdf install
elixir 1.5.3 is already installed
erlang 20.1 is already installed
ruby 2.5.3 is already installed
```

**Comment by SeanSith** [comment]
Yes, the feature has not been built, yet. This isn't an issue with asdf-ruby, but with asdf-vm itself. The function which searches for `.tool-version` files in `utils.sh` probably needs augmented to check for legacy file support. I'm sure the maintainers would love a PR on the issue I linked above.

**Comment by nicktime** [comment]
Ok, closing then in favor of https://github.com/asdf-vm/asdf/issues/269
