### ISSUE TITLE
Unrecognized archive format: Ruby 2.6.0

### ISSUE THREAD

**Issue by ksolo** [asdf-vm/asdf-ruby#89]
## What

When attempting to install Ruby 2.6.0 or any of the 2.6.x series, including the RC versions I receive the `Unrecognizable archive format` error. I can install Ruby 2.5.x without issue.

```
$ asdf install ruby 2.6.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   297  100   297    0     0   1607      0 --:--:-- --:--:-- --:--:--  1614
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```
When I execute this command, even though the install fails, asdf shows 2.6.0 as an installed version and when I run the command again, it says it's already install.

OS: Mac 10.14.2

**Comment by Stratus3D** [comment]
I have installed Ruby 2.6.0 and an RC version on my OSX 10.14.1 machine and it worked. Can you provide any more information on this issue? I will try upgrading to 10.14.2 tonight and see if that has any affect on this.

**Comment by ksolo** [comment]
I'm using `asdf` version 0.6.2

I was able to install 2.6.0 preview1, preview2, the problem seems to start at preview 3 and above
```
2.6.0-preview1 -- ok
2.6.0-preview2 -- ok
2.6.0-preview3 -- fail
2.6.0-rc1      -- fail
2.6.0-rc2      -- fail
2.6.0          -- fail
```

Happy to provide anything else you think would be helpful.

**Comment by Stratus3D** [comment]
I upgraded to 10.14.2 last night, and I tried installing 2.6.0-rc2 since I did not have that version already installed:

```
ruby-build: use openssl from homebrew
Downloading ruby-2.6.0-rc2.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.0-rc2.tar.bz2
Installing ruby-2.6.0-rc2...
ruby-build: use readline from homebrew
Installed ruby-2.6.0-rc2 to [redacted]/.asdf/installs/ruby/2.6.0-rc2
```

Can you make sure you are using the latest version of this plugin? `asdf plugin-update ruby`

**Comment by ksolo** [comment]
That worked. I really appreciate your help with this.

Closing the issue.
