### ISSUE TITLE
unbound variable

### ISSUE THREAD

**Issue by AlanGabbianelli** [asdf-vm/asdf-ruby#99]
Hi,

First of all, thank you for this project and your efforts in maintaining it! 💪

Yesterday, I updated `asdf-ruby` in order to be able to install `ruby 2.6.1`, and I am currently using `master` (commit `59c628551efafd8bd443978228b664f158f93165`).

The problem I am facing is that whenever I try to install any version of ruby, it fails and I get an `unbound variable` error, as you can see here:
```
➜  ~ asdf install ruby 2.6.1
ruby-build: use openssl from homebrew
Downloading ruby-2.6.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.1.tar.bz2
Installing ruby-2.6.1...
ruby-build: use readline from homebrew
Installed ruby-2.6.1 to /Users/alangabbianelli/.asdf/installs/ruby/2.6.1


/Users/alangabbianelli/.asdf/plugins/ruby/bin/install: line 84: args[@]: unbound variable
```

As a quick and dirty fix, I simply removed [the problematic lines in `bin/install`](https://github.com/asdf-vm/asdf-ruby/blob/master/bin/install#L84-L90):
```
    echo -n "Running: gem install "$gem_name" "${args[@]}" ... "

    if $gem install "$gem_name" "${args[@]}" > /dev/null 2>&1; then
      echo -e "SUCCESS"
    else
      echo -e "FAIL"
    fi
```

Without those lines, that from what I understand are there just to print some information to the console, I was able to install `ruby 2.6.1` and any other supported version.

Sorry for opening an issue and not a PR to fix the problem, but bash is not my strong suit.

Thanks,

Alan

**Comment by Stratus3D** [comment]
It looks like this was introduced by https://github.com/asdf-vm/asdf-ruby/pull/98

**Comment by grossadamm** [comment]
Also seeing this issue, I'm trying to figure out a workaround

**Comment by grossadamm** [comment]
Ok, as a workaround, I've emptied out my `~/.default-gems`. I can now install rubies again

**Comment by idoo** [comment]
@grossadamm it's not related to default-gems, just brew updates issues

**Comment by BilalBudhani** [comment]
@idoo I think it is `default-gems` related issue. I just faced the same issue and following @grossadamm's suggested workaround worked for me.

**Comment by Stratus3D** [comment]
I think I fixed this. Anyone want to test out my PR branch?

**Comment by grossadamm** [comment]
I can give it a go on Tuesday. Maybe someone can get to it faster?
